import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
    en: {
        // General
        'dashboard': 'Dashboard',
        'tickets': 'Tickets',
        'settings': 'Settings',
        'profile': 'Profile',
        'logout': 'Logout',
        'cancel': 'Cancel',
        'confirm': 'Confirm',
        'save': 'Save Changes',
        'edit': 'Edit',
        'search': 'Search...',
        'actions': 'Actions',
        'delete': 'Delete',
        'active': 'Active',
        'inactive': 'Inactive',
        'notifications': 'Notifications',
        'ticket': 'Ticket',
        'allTickets': 'All Tickets',
        'department': 'Department',
        'noData': 'No data available',
        
        // Auth
        'signIn': 'Sign In',
        'createAccount': 'Create Account',
        'email': 'Email Address',
        'password': 'Password',
        'rememberMe': 'Remember me',
        'forgotPassword': 'Forgot Password?',
        'noAccount': "Don't have an account?",
        'registerHere': 'Register',
        'enterCredentials': 'Enter your credentials to access the system.',
        'registerDesc': 'Register to submit IT support requests.',
        
        // TopBar / Profile Dropdown
        'editProfile': 'Edit Profile',
        'language': 'English',
        'logoutConfirmTitle': 'Confirm Logout',
        'logoutConfirmDesc': 'Are you sure you want to log out of your account? You will need to sign in again to access your tickets.',
        'loggingOut': 'Logging out...',

        // Sidebar
        'myTickets': 'My Tickets',
        'createTicket': 'Create Ticket',
        'reports': 'Reports',
        'broadcast': 'Broadcast',
        'adminDashboard': 'Admin Dashboard',
        'auditLog': 'Audit Log',
        'documentation': 'Documentation',
        'users': 'Users',
        
        // Dashboard
        'totalTickets': 'Total Tickets',
        'open': 'Open',
        'inProgress': 'In Progress',
        'closed': 'Closed',
        'urgent': 'Urgent',
        'unassigned': 'Unassigned',
        'recentTickets': 'Recent Tickets',
        'viewAll': 'View All',
        'welcomeBack': 'Welcome back',
        'quickActions': 'Quick Actions',
        'priorityQueue': 'Priority Queue',
        'highPriority': 'High priority and unassigned tickets',
        'allClear': 'All clear',
        'noUrgent': 'No urgent or unassigned tickets require immediate attention.',
        'recentActivity': 'Recent Activity',
        'systemActions': 'System actions and updates',
        'noRecentActivity': 'No recent activity',
        'systemEventsAppear': 'System events will appear here.',
        'status': 'Status',
        'priority': 'Priority',
        'ticketId': 'Ticket ID',
        'title': 'Title',
        'date': 'Date',
        'admin': 'Admin',
        'userManagement': 'User Management',
        'manageUsersDesc': 'Manage user accounts and roles.',
        'user': 'User',
        'department': 'Department',
        'role': 'Role',
        'lastLogin': 'Last Login',
        'joined': 'Joined',
        'never': 'Never',
        'noUsersFound': 'No users found.',
        'showing': 'Showing',
        'of': 'of',
        'searchUsers': 'Search name, email, or department...',

        // Profile Page
        'profileSettings': 'Profile Settings',
        'profileSettingsDesc': 'Manage your account details and preferences.',
        'personalInfo': 'Personal Information',
        'personalInfoDesc': 'Update your basic profile details.',
        'fullName': 'Full Name',
        'changePhoto': 'Change Photo',
        'uploadPhoto': 'Upload Photo',
        'cropPhoto': 'Crop your photo',
        'zoom': 'Zoom',
        'security': 'Security',
        'securityDesc': 'Manage your password and security settings.',
        'currentPassword': 'Current Password',
        'newPassword': 'New Password',
        'confirmPassword': 'Confirm Password',
        'updatePassword': 'Update Password',
        'saveChanges': 'Save Changes',
        'saving': 'Saving...',
        
        // Notifications
        'stayUpdated': 'Stay updated on your ticket activity.',
        'markAllAsRead': 'Mark all as read',
        'ticket': 'Ticket',
        'markRead': 'Mark read',
        'page': 'Page',
        'noNotifications': 'No notifications',
        'allCaughtUp': 'You are all caught up.',
        'allTickets': 'All Tickets',
        'manageAllTickets': 'Manage all support tickets across the organization.',
        'filters': 'Filters',
        'searchPlaceholder': 'Search ID, title, or requester...',
        'allStatus': 'All Status',
        'allPriority': 'All Priority',
        'allAssignee': 'All Assignee',
        'exportCsv': 'Export CSV',
        'id': 'ID',
        'requester': 'Requester',
        'category': 'Category',
        'assigned': 'Assigned',
        'noTicketsFound': 'No tickets found',
        'adjustFilters': 'Try adjusting your filters.',
        'systemReports': 'System Reports',
        'reportsDesc': 'Analytics and performance metrics.',
        'filter': 'Filter',
        'closedTickets': 'Closed Tickets',
        'resolutionRate': 'Resolution Rate',
        'avgResolution': 'Avg. Resolution (Days)',
        'ticketsByStatus': 'Tickets by Status',
        'ticketsByPriority': 'Tickets by Priority',
        'ticketsByCategory': 'Tickets by Category',
        'ticketVolumeTrend': 'Ticket Volume Trend',
        'noData': 'No data available.',
        'noTicketData': 'No ticket data for this period.',
        'auditLogDesc': 'System activity history and audit trail.',
        'allActions': 'All Actions',
        'searchDesc': 'Search description...',
        'action': 'Action',
        'description': 'Description',
        'ip': 'IP',
        'noAuditLogs': 'No audit logs found.',
        'systemSettings': 'System Settings',
        'settingsDesc': 'Configure system parameters and ticket categories.',
        'configuration': 'Configuration',
        'ticketCategories': 'Ticket Categories',
        'cannedResponses': 'Canned Responses',
        'addCategory': 'Add Ticket Category',
        'addCategoryDesc': 'Create a new category for support tickets.',
        'categoryName': 'Category Name',
        'categoryDesc': 'Description (Optional)',
        'briefDesc': 'Brief description of this category',
        'manageCategories': 'Manage Categories',
        'manageCategoriesDesc': 'Enable or disable categories for new tickets.',
        'name': 'Name',
        'disable': 'Disable',
        'enable': 'Enable',
        'noCategories': 'No categories found.',
        'addMacro': 'Add Canned Response',
        'addMacroDesc': 'Create reply templates for fast responses.',
        'templateTitle': 'Template Title',
        'responseBody': 'Response Body',
        'writeTemplate': 'Write the template content here...',
        'addTemplate': 'Add Template',
        'manageMacros': 'Manage Canned Responses',
        'manageMacrosDesc': 'Enable or disable templates.',
        'noTemplates': 'No templates found.',
        
        // Profile additional
        'phoneNumber': 'Phone Number',
        'phonePlaceholder': '081234567890',
        'phoneHint': 'Numbers only, 9–15 digits.',
        'departmentAdminOnly': 'Department can only be changed by an Admin.',
        'contactAdminToChange': 'Contact administrator to change.',
        'min8chars': 'Minimum 8 characters',

        // Broadcast
        'broadcastNotification': 'Broadcast Notification',
        'broadcastDesc': 'Send system alerts or messages to users.',
        'messageContent': '1. Message Content',
        'notificationTitle': 'Notification Title',
        'egMaintenance': 'e.g. System Maintenance',
        'messageLabel': 'Message',
        'enterDetails': 'Enter the notification details...',
        'typeLabel': 'Type',
        'infoBlue': 'Info (Blue)',
        'successGreen': 'Success (Green)',
        'warningYellow': 'Warning (Yellow)',
        'errorRed': 'Error (Red)',
        'targetAudience': '2. Target Audience',
        'allUsers': 'All Users',
        'everyoneInSystem': 'Everyone in system',
        'byDepartment': 'By Department',
        'specificDepartment': 'Specific department',
        'specificUsers': 'Specific Users',
        'selectIndividuals': 'Select individuals',
        'selectDepartment': 'Select Department',
        'selectADepartment': 'Select a department...',
        'usersSelected': 'user(s) selected',
        'sendBroadcast': 'Broadcast Notification',

        // Profile Extended
        'profileInformation': 'Profile Information',
        'preferences': 'Preferences',
        'activity': 'Activity Log',
        'languagePref': 'Language Preference',
        'notificationPref': 'Notification Preference',
        'selectLanguage': 'Select Language',
        'english': 'English',
        'indonesian': 'Indonesian',
        'emailNotifications': 'Email Notifications',
        'appNotifications': 'In-App Notifications',
        'receiveEmailUpdates': 'Receive updates about tickets via email',
        'receiveAppUpdates': 'Receive system notifications in the app',
        'auditHistory': 'Audit History',
        'noActivityLogs': 'No activity logs found.',
        'accountSummary': 'Account Summary',
        'roleLabel': 'Role',
        'departmentLabel': 'Department',
        'joinedLabel': 'Joined',
        'lastLoginLabel': 'Last Login',
        'removePhoto': 'Remove Photo',
        'uploading': 'Uploading...',
        'removing': 'Removing...',
        'cancelCrop': 'Cancel',
        'applyCrop': 'Apply',
        'cropPhoto': 'Crop Photo',
        'zoom': 'Zoom',

        // Ticket Create/Index (User)
        'createNewTicket': 'Create New Ticket',
        'createTicketDesc': 'Describe your issue and we will assist you as soon as possible.',
        'titleHelpText': 'Briefly describe the issue.',
        'titlePlaceholder': 'e.g. Printer not working in Room 204',
        'selectCategory': 'Select category',
        'low': 'Low',
        'medium': 'Medium',
        'high': 'High',
        'critical': 'Critical',
        'descriptionPlaceholder': 'Provide detailed information including steps to reproduce.',
        'attachmentsOptional': 'Attachments (optional)',
        'attachmentHint': 'Max 5 files, 10MB each. Supported: images, PDF, Office documents, markdown, ZIP.',
        'submitTicket': 'Submit Ticket',
        'trackTicketsDesc': 'Track and manage your support requests.',
        'newTicket': 'New Ticket',
        'searchByIdOrTitle': 'Search by ID or title...',
        'reopened': 'Reopened',
        'createFirstTicket': 'Create your first ticket to get started.',
        'notifications': 'Notifications',

        // Notification Operations Center
        'notificationOperationsCenter': 'Notification Operations Center',
        'notificationOperationsCenterDesc': 'Manage broadcasts, templates, and automated notifications.',
        'newBroadcast': 'New Broadcast',
        'overview': 'Overview',
        'broadcasts': 'Broadcasts',
        'templates': 'Templates',
        'automation': 'Automation',
        'totalBroadcasts': 'Total Broadcasts',
        'completed': 'Completed',
        'scheduled': 'Scheduled',
        'failed': 'Failed',
        'recentBroadcasts': 'Recent Broadcasts',
        'viewAll': 'View All',
        'type': 'Type',
        'noBroadcastsFound': 'No broadcasts found',
        'noBroadcastsDesc': "You haven't sent any broadcasts yet.",
        'createBroadcast': 'Create Broadcast',
        'systemCapacity': 'System Capacity',
        'monthlyQuota': 'Monthly Quota',
        'unlimited': 'Unlimited',
        'info': 'Info',
        'success': 'Success',
        'warning': 'Warning',
        'error': 'Error',
        'draft': 'Draft',
        'processing': 'Processing',

        // Reports Dashboard
        'rpt_title': 'Reporting Dashboard',
        'rpt_subtitle': 'Comprehensive analytics and performance insights.',
        'rpt_tickets': 'Tickets',
        'rpt_opened': 'Opened',
        'rpt_resolved': 'Resolved',
        'rpt_pending': 'Pending',
        'rpt_overdue': 'Overdue',
        'rpt_avgResTime': 'Avg. Resolution',
        'rpt_slaCompliance': 'SLA Compliance',
        'rpt_resolvedToday': 'Resolved Today',
        'rpt_reopened': 'Reopened',
        'rpt_satisfaction': 'Satisfaction',
        'rpt_vsPrev': 'vs previous period',
        'rpt_openVsResolved': 'Opened vs Resolved',
        'rpt_openVsResolvedDesc': 'Compare new tickets against resolved throughput.',
        'rpt_resolutionTrend': 'Resolution Time Trend',
        'rpt_resolutionTrendDesc': 'Average resolution time in hours per day.',
        'rpt_slaOverview': 'SLA Overview',
        'rpt_compliance': 'Compliance',
        'rpt_withinSla': 'Within SLA',
        'rpt_breached': 'Breached',
        'rpt_slaTrend': 'SLA Compliance Trend',
        'rpt_slaTrendDesc': 'Daily SLA compliance rate over time.',
        'rpt_techPerformance': 'Technician Performance',
        'rpt_techPerformanceDesc': 'Workload breakdown per technician.',
        'rpt_activityHeatmap': 'Activity Heatmap',
        'rpt_activityHeatmapDesc': 'Ticket creation patterns by day and hour.',
        'rpt_less': 'Less',
        'rpt_more': 'More',
        'rpt_lifecycle': 'Ticket Lifecycle Funnel',
        'rpt_lifecycleDesc': 'Flow from creation to resolution.',
        'rpt_reopenedAnalytics': 'Reopened Tickets',
        'rpt_reopenedCount': 'Reopened',
        'rpt_reopenRate': 'Reopen Rate',
        'rpt_prevPeriod': 'Prev. Period',
        'rpt_reopenedInsight': 'A high reopen rate may indicate incomplete initial resolution or unclear problem definition.',
        'rpt_avgRating': 'Average Rating',
        'rpt_ratings': 'ratings',
        'rpt_avgHours': 'Avg. Hours',
        'rpt_export': 'Export',
        'rpt_today': 'Today',
        'rpt_7d': '7 Days',
        'rpt_30d': '30 Days',
        'rpt_90d': '90 Days',

        // Ticket Detail
        'td_description': 'Description',
        'td_solutionNotes': 'Solution Notes',
        'td_attachments': 'Attachments',
        'td_activity': 'Activity',
        'td_noActivity': 'No activity yet.',
        'td_writeComment': 'Write a comment...',
        'td_writeCommentAdmin': 'Write a comment or internal note...',
        'td_internalNote': 'Internal note',
        'td_internalNoteDesc': 'Internal note (not visible to user)',
        'td_postComment': 'Post Comment',
        'td_post': 'Post',
        'td_details': 'Details',
        'td_requester': 'Requester',
        'td_assignedTo': 'Assigned To',
        'td_unassigned': 'Unassigned',
        'td_created': 'Created',
        'td_estimatedResolution': 'Estimated Resolution',
        'td_slaDeadline': 'SLA Deadline',
        'td_closed': 'Closed',
        'td_yourFeedback': 'Your Feedback',
        'td_rateExperience': 'Rate your experience',
        'td_rateDesc': 'How satisfied are you with the resolution of this ticket?',
        'td_additionalFeedback': 'Any additional feedback? (Optional)',
        'td_submitFeedback': 'Submit Feedback',
        'td_issueNotResolved': 'Issue not resolved?',
        'td_issueNotResolvedDesc': 'If you are still experiencing the same issue, you can reopen this ticket.',
        'td_reopenTicket': 'Reopen Ticket',
        'td_files': 'file(s)',
        'td_internal': 'Internal',
        'td_assignedToBy': 'Assigned to',
        'td_by': 'by',
        'td_updateStatus': 'Update Status',
        'td_addResolutionDetails': 'Add resolution details...',
        'td_assignTicket': 'Assign Ticket',
        'td_assignTo': 'Assign To',
        'td_selectStaff': 'Select staff member',
        'td_assignmentNotes': 'Notes (optional)',
        'td_assignmentNotesPlaceholder': 'Assignment notes...',
        'td_assign': 'Assign',
        'td_insertTemplate': 'Insert template...',
        'td_userSatisfaction': 'User Satisfaction',
        'td_name': 'Name',

        // Notification Templates
        'nt_templates': 'Notification Templates',
        'nt_templatesDesc': 'Manage reusable notification templates for broadcasts and automation.',
        'nt_newTemplate': 'New Template',
        'nt_searchTemplates': 'Search templates...',
        'nt_noTemplatesYet': 'No templates created yet.',
        'nt_noMatchingTemplates': 'No templates match your search.',
        'nt_createFirstTemplate': 'Create your first template',
        'nt_templatePreview': 'Template Preview',
        'nt_templateName': 'Template Name',
        'nt_subject': 'Subject',
        'nt_content': 'Content',
        'nt_variables': 'Variables',
        'nt_preview': 'Preview',
        'nt_confirmDelete': 'Are you sure you want to delete this template?',
        'nt_deactivate': 'Deactivate',
        'nt_activate': 'Activate',

        // Notification Automation
        'na_automation': 'Notification Automation',
        'na_automationDesc': 'Configure automated notification rules triggered by system events.',
        'na_newRule': 'New Rule',
        'na_searchRules': 'Search rules...',
        'na_noRulesYet': 'No automation rules created yet.',
        'na_noMatchingRules': 'No rules match your search.',
        'na_createFirstRule': 'Create your first automation rule',
        'na_totalRules': 'Total Rules',
        'na_confirmDelete': 'Are you sure you want to delete this automation rule?',
        'na_createRuleDesc': 'Define a trigger event and link it to a notification template.',
        'na_ruleName': 'Rule Name',
        'na_ruleNamePlaceholder': 'e.g. Notify on ticket creation',
        'na_triggerEvent': 'Trigger Event',
        'na_selectEvent': 'Select a trigger event...',
        'na_template': 'Notification Template',
        'na_selectTemplate': 'Select a template...',
        'na_actionConfig': 'Action Configuration',
        'na_inAppNotification': 'In-App Notification',
        'na_inAppDesc': 'Show notification in the user notification panel.',
        'na_emailNotification': 'Email Notification',
        'na_emailDesc': 'Send email to the affected user.',
        'na_activeOnCreateDesc': 'Rule will start processing events immediately.',
        'na_createRule': 'Create Rule',

        // Template Create
        'nt_createTemplateDesc': 'Create a reusable notification template with dynamic variables.',
        'nt_templateNamePlaceholder': 'e.g. Ticket Status Update',
        'nt_subjectPlaceholder': 'e.g. Your ticket #{{ticket_number}} has been updated',
        'nt_contentPlaceholder': 'Write your notification content here. Use {{variable}} syntax for dynamic values.',
        'nt_variablesHint': 'Define variables that can be used in the subject and content. Click a variable to insert it into the content.',
        'nt_addVariablePlaceholder': 'Variable name (e.g. ticket_number)',
        'nt_clickToInsert': 'Click to insert into content',
        'nt_activeOnCreate': 'Active on creation',
        'nt_activeOnCreateDesc': 'Template will be immediately available for use.',
        'nt_createTemplate': 'Create Template',

        // User Notifications Page
        'nf_subtitle': 'Stay updated with your ticket activity and system alerts.',
        'nf_all': 'All',
        'nf_unread': 'Unread',
        'nf_read': 'Read',
        'nf_clearRead': 'Clear Read',
        'nf_totalNotifications': 'Total',
        'nf_today': 'Today',
        'nf_details': 'Details',
        'nf_message': 'Message',
        'nf_assignedTo': 'Assigned To',
        'nf_time': 'Time',
        'nf_viewTicket': 'View Ticket',
        'nf_total': 'total',
        'nf_emptyDesc': 'When you receive notifications about ticket updates, they will appear here.',
        'nf_confirmClearRead': 'Are you sure you want to delete all read notifications?',

        // Admin Notification Dashboard
        'nda_title': 'Notification Operations Center',
        'nda_subtitle': 'Manage broadcasts, templates, automation, and monitor system notifications.',
        'nda_overviewDesc': 'Dashboard & Metrics',
        'nda_broadcastsDesc': 'Send & manage',
        'nda_rulesActive': 'rules active',
        'nda_systemNotifs': 'System Notifs',
        'nda_recentSystemNotifs': 'Recent System Notifications',
        'nda_recentSystemNotifsDesc': 'Latest notifications across all users.',
        'nda_noSystemNotifs': 'No system notifications yet.',
        'nda_broadcastsTableDesc': 'Last 5 broadcast messages.',
        'nda_by': 'by',
        'nda_automationRules': 'Automation Rules',
        'nda_monthlyQuota': 'Monthly Quota',
        'nda_draft': 'Draft',
        'nda_processing': 'Processing',
        'nda_info': 'Info',
        'nda_success': 'Success',
        'nda_danger': 'Danger',
    },
    id: {
        // General
        'dashboard': 'Beranda',
        'tickets': 'Tiket',
        'settings': 'Pengaturan',
        'profile': 'Profil',
        'logout': 'Keluar',
        'cancel': 'Batal',
        'confirm': 'Konfirmasi',
        'save': 'Simpan Perubahan',
        'edit': 'Ubah',
        'search': 'Cari...',
        'actions': 'Aksi',
        'delete': 'Hapus',
        'active': 'Aktif',
        'inactive': 'Nonaktif',
        'notifications': 'Notifikasi',
        'ticket': 'Tiket',
        'allTickets': 'Semua Tiket',
        'department': 'Departemen',
        'noData': 'Tidak ada data tersedia',
        
        // Auth
        'signIn': 'Masuk',
        'createAccount': 'Buat Akun',
        'email': 'Alamat Email',
        'password': 'Kata Sandi',
        'rememberMe': 'Ingat saya',
        'forgotPassword': 'Lupa Kata Sandi?',
        'noAccount': "Belum memiliki akun?",
        'registerHere': 'Daftar',
        'enterCredentials': 'Masukkan kredensial Anda untuk mengakses sistem.',
        'registerDesc': 'Daftar untuk mengirimkan permintaan dukungan IT.',
        
        // TopBar / Profile Dropdown
        'editProfile': 'Ubah Profil',
        'language': 'Bahasa Indonesia',
        'logoutConfirmTitle': 'Konfirmasi Keluar',
        'logoutConfirmDesc': 'Apakah Anda yakin ingin keluar dari akun Anda? Anda harus masuk kembali untuk mengakses tiket Anda.',
        'loggingOut': 'Keluar...',

        // Sidebar
        'myTickets': 'Tiket Saya',
        'createTicket': 'Buat Tiket',
        'reports': 'Laporan',
        'broadcast': 'Notifikasi',
        'adminDashboard': 'Beranda Admin',
        'auditLog': 'Log Audit',
        'documentation': 'Dokumentasi',
        'users': 'Pengguna',
        'notifications': 'Notifikasi',
        
        // Dashboard
        'totalTickets': 'Total Tiket',
        'open': 'Buka',
        'inProgress': 'Diproses',
        'closed': 'Selesai',
        'urgent': 'Mendesak',
        'unassigned': 'Belum Ditugaskan',
        'recentTickets': 'Tiket Terbaru',
        'viewAll': 'Lihat Semua',
        'welcomeBack': 'Selamat datang kembali',
        'quickActions': 'Aksi Cepat',
        'priorityQueue': 'Antrean Prioritas',
        'highPriority': 'Tiket prioritas tinggi dan belum ditugaskan',
        'allClear': 'Semua aman',
        'noUrgent': 'Tidak ada tiket mendesak yang memerlukan perhatian segera.',
        'recentActivity': 'Aktivitas Terbaru',
        'systemActions': 'Tindakan dan pembaruan sistem',
        'noRecentActivity': 'Tidak ada aktivitas terbaru',
        'systemEventsAppear': 'Peristiwa sistem akan muncul di sini.',
        'status': 'Status',
        'priority': 'Prioritas',
        'ticketId': 'ID Tiket',
        'title': 'Judul',
        'date': 'Tanggal',
        'admin': 'Admin',
        'userManagement': 'Manajemen Pengguna',
        'manageUsersDesc': 'Kelola akun pengguna dan peran.',
        'user': 'Pengguna',
        'department': 'Departemen',
        'role': 'Peran',
        'lastLogin': 'Terakhir Masuk',
        'joined': 'Bergabung',
        'never': 'Belum Pernah',
        'noUsersFound': 'Tidak ada pengguna yang ditemukan.',
        'showing': 'Menampilkan',
        'of': 'dari',
        'searchUsers': 'Cari nama, email, atau departemen...',

        // Profile Page
        'profileSettings': 'Pengaturan Profil',
        'profileSettingsDesc': 'Kelola detail dan preferensi akun Anda.',
        'personalInfo': 'Informasi Pribadi',
        'personalInfoDesc': 'Perbarui detail profil dasar Anda.',
        'fullName': 'Nama Lengkap',
        'changePhoto': 'Ubah Foto',
        'uploadPhoto': 'Unggah Foto',
        'cropPhoto': 'Potong foto Anda',
        'zoom': 'Perbesar',
        'security': 'Keamanan',
        'securityDesc': 'Kelola kata sandi dan pengaturan keamanan Anda.',
        'currentPassword': 'Kata Sandi Saat Ini',
        'newPassword': 'Kata Sandi Baru',
        'confirmPassword': 'Konfirmasi Kata Sandi',
        'updatePassword': 'Perbarui Kata Sandi',
        'saveChanges': 'Simpan Perubahan',
        'saving': 'Menyimpan...',
        
        // Notifications
        'stayUpdated': 'Tetap perbarui aktivitas tiket Anda.',
        'markAllAsRead': 'Tandai semua telah dibaca',
        'ticket': 'Tiket',
        'markRead': 'Tandai dibaca',
        'page': 'Halaman',
        'noNotifications': 'Tidak ada notifikasi',
        'allCaughtUp': 'Semua sudah beres.',
        'allTickets': 'Semua Tiket',
        'manageAllTickets': 'Kelola semua tiket dukungan di seluruh organisasi.',
        'filters': 'Filter',
        'searchPlaceholder': 'Cari ID, judul, atau pemohon...',
        'allStatus': 'Semua Status',
        'allPriority': 'Semua Prioritas',
        'allAssignee': 'Semua Petugas',
        'exportCsv': 'Ekspor CSV',
        'id': 'ID',
        'requester': 'Pemohon',
        'category': 'Kategori',
        'assigned': 'Ditugaskan',
        'noTicketsFound': 'Tidak ada tiket ditemukan',
        'adjustFilters': 'Coba sesuaikan filter Anda.',
        'systemReports': 'Laporan Sistem',
        'reportsDesc': 'Metrik analitik dan kinerja.',
        'filter': 'Filter',
        'closedTickets': 'Tiket Selesai',
        'resolutionRate': 'Tingkat Penyelesaian',
        'avgResolution': 'Rata-rata Penyelesaian (Hari)',
        'ticketsByStatus': 'Tiket berdasarkan Status',
        'ticketsByPriority': 'Tiket berdasarkan Prioritas',
        'ticketsByCategory': 'Tiket berdasarkan Kategori',
        'ticketVolumeTrend': 'Tren Volume Tiket',
        'noData': 'Tidak ada data tersedia.',
        'noTicketData': 'Tidak ada data tiket untuk periode ini.',
        'auditLogDesc': 'Riwayat aktivitas sistem dan jejak audit.',
        'allActions': 'Semua Aksi',
        'searchDesc': 'Cari deskripsi...',
        'action': 'Aksi',
        'description': 'Deskripsi',
        'ip': 'IP',
        'noAuditLogs': 'Tidak ada log audit ditemukan.',
        'systemSettings': 'Pengaturan Sistem',
        'settingsDesc': 'Konfigurasi parameter sistem dan kategori tiket.',
        'configuration': 'Konfigurasi',
        'ticketCategories': 'Kategori Tiket',
        'cannedResponses': 'Tanggapan Cepat',
        'addCategory': 'Tambah Kategori Tiket',
        'addCategoryDesc': 'Buat kategori baru untuk tiket dukungan.',
        'categoryName': 'Nama Kategori',
        'categoryDesc': 'Deskripsi (Opsional)',
        'briefDesc': 'Deskripsi singkat tentang kategori ini',
        'manageCategories': 'Kelola Kategori',
        'manageCategoriesDesc': 'Aktifkan atau nonaktifkan kategori untuk tiket baru.',
        'name': 'Nama',
        'disable': 'Nonaktifkan',
        'enable': 'Aktifkan',
        'noCategories': 'Tidak ada kategori ditemukan.',
        'addMacro': 'Tambah Tanggapan Cepat',
        'addMacroDesc': 'Buat templat balasan untuk tanggapan cepat.',
        'templateTitle': 'Judul Templat',
        'responseBody': 'Isi Tanggapan',
        'writeTemplate': 'Tulis konten templat di sini...',
        'addTemplate': 'Tambah Templat',
        'manageMacros': 'Kelola Tanggapan Cepat',
        'manageMacrosDesc': 'Aktifkan atau nonaktifkan templat.',
        'noTemplates': 'Tidak ada templat ditemukan.',
        
        // Profile additional
        'phoneNumber': 'Nomor Telepon',
        'phonePlaceholder': '081234567890',
        'phoneHint': 'Hanya angka, 9–15 digit.',
        'departmentAdminOnly': 'Departemen hanya dapat diubah oleh Admin.',
        'contactAdminToChange': 'Hubungi administrator untuk mengubah.',
        'min8chars': 'Minimal 8 karakter',

        // Broadcast
        'broadcastNotification': 'Notifikasi Siaran',
        'broadcastDesc': 'Kirim peringatan sistem atau pesan ke pengguna.',
        'messageContent': '1. Isi Pesan',
        'notificationTitle': 'Judul Notifikasi',
        'egMaintenance': 'mis. Pemeliharaan Sistem',
        'messageLabel': 'Pesan',
        'enterDetails': 'Masukkan detail notifikasi...',
        'typeLabel': 'Tipe',
        'infoBlue': 'Info (Biru)',
        'successGreen': 'Sukses (Hijau)',
        'warningYellow': 'Peringatan (Kuning)',
        'errorRed': 'Kesalahan (Merah)',
        'targetAudience': '2. Target Pengguna',
        'allUsers': 'Semua Pengguna',
        'everyoneInSystem': 'Semua orang dalam sistem',
        'byDepartment': 'Berdasarkan Departemen',
        'specificDepartment': 'Departemen tertentu',
        'specificUsers': 'Pengguna Tertentu',
        'selectIndividuals': 'Pilih individu',
        'selectDepartment': 'Pilih Departemen',
        'selectADepartment': 'Pilih departemen...',
        'usersSelected': 'pengguna dipilih',
        'sendBroadcast': 'Kirim Notifikasi',

        // Profile Extended
        'profileInformation': 'Informasi Profil',
        'preferences': 'Preferensi',
        'activity': 'Log Aktivitas',
        'languagePref': 'Preferensi Bahasa',
        'notificationPref': 'Preferensi Notifikasi',
        'selectLanguage': 'Pilih Bahasa',
        'english': 'Bahasa Inggris',
        'indonesian': 'Bahasa Indonesia',
        'emailNotifications': 'Notifikasi Email',
        'appNotifications': 'Notifikasi Dalam Aplikasi',
        'receiveEmailUpdates': 'Terima pembaruan tentang tiket via email',
        'receiveAppUpdates': 'Terima notifikasi sistem di aplikasi',
        'auditHistory': 'Riwayat Audit',
        'noActivityLogs': 'Tidak ada log aktivitas.',
        'accountSummary': 'Ringkasan Akun',
        'roleLabel': 'Peran',
        'departmentLabel': 'Departemen',
        'joinedLabel': 'Bergabung',
        'lastLoginLabel': 'Terakhir Masuk',
        'removePhoto': 'Hapus Foto',
        'uploading': 'Mengunggah...',
        'removing': 'Menghapus...',
        'cancelCrop': 'Batal',
        'applyCrop': 'Terapkan',
        'cropPhoto': 'Potong Foto',
        'zoom': 'Perbesar',

        // Ticket Create/Index (User)
        'createNewTicket': 'Buat Tiket Baru',
        'createTicketDesc': 'Jelaskan masalah Anda dan kami akan membantu secepatnya.',
        'titleHelpText': 'Jelaskan masalah secara singkat.',
        'titlePlaceholder': 'mis. Printer tidak berfungsi di Ruang 204',
        'selectCategory': 'Pilih kategori',
        'low': 'Rendah',
        'medium': 'Sedang',
        'high': 'Tinggi',
        'critical': 'Kritis',
        'descriptionPlaceholder': 'Berikan informasi lengkap termasuk langkah-langkah untuk mereproduksi masalah.',
        'attachmentsOptional': 'Lampiran (opsional)',
        'attachmentHint': 'Maks 5 berkas, 10MB per berkas. Didukung: gambar, PDF, dokumen Office, markdown, ZIP.',
        'submitTicket': 'Kirim Tiket',
        'trackTicketsDesc': 'Lacak dan kelola permintaan dukungan Anda.',
        'newTicket': 'Tiket Baru',
        'searchByIdOrTitle': 'Cari berdasarkan ID atau judul...',
        'reopened': 'Dibuka Kembali',
        'createFirstTicket': 'Buat tiket pertama Anda untuk memulai.',
        'notifications': 'Notifikasi',

        // Notification Operations Center
        'notificationOperationsCenter': 'Pusat Operasi Notifikasi',
        'notificationOperationsCenterDesc': 'Kelola siaran, templat, dan notifikasi otomatis.',
        'newBroadcast': 'Siaran Baru',
        'overview': 'Ringkasan',
        'broadcasts': 'Siaran',
        'templates': 'Templat',
        'automation': 'Otomasi',
        'totalBroadcasts': 'Total Siaran',
        'completed': 'Selesai',
        'scheduled': 'Terjadwal',
        'failed': 'Gagal',
        'recentBroadcasts': 'Siaran Terbaru',
        'viewAll': 'Lihat Semua',
        'type': 'Tipe',
        'noBroadcastsFound': 'Belum ada siaran',
        'noBroadcastsDesc': 'Anda belum mengirim siaran apa pun.',
        'createBroadcast': 'Buat Siaran',
        'systemCapacity': 'Kapasitas Sistem',
        'monthlyQuota': 'Kuota Bulanan',
        'unlimited': 'Tak Terbatas',
        'info': 'Info',
        'success': 'Berhasil',
        'warning': 'Peringatan',
        'error': 'Kesalahan',
        'draft': 'Draf',
        'processing': 'Diproses',

        // Reports Dashboard
        'rpt_title': 'Dasbor Pelaporan',
        'rpt_subtitle': 'Analitik komprehensif dan wawasan kinerja.',
        'rpt_tickets': 'Tiket',
        'rpt_opened': 'Dibuka',
        'rpt_resolved': 'Diselesaikan',
        'rpt_pending': 'Tertunda',
        'rpt_overdue': 'Terlambat',
        'rpt_avgResTime': 'Rata-rata Resolusi',
        'rpt_slaCompliance': 'Kepatuhan SLA',
        'rpt_resolvedToday': 'Diselesaikan Hari Ini',
        'rpt_reopened': 'Dibuka Kembali',
        'rpt_satisfaction': 'Kepuasan',
        'rpt_vsPrev': 'vs periode sebelumnya',
        'rpt_openVsResolved': 'Dibuka vs Diselesaikan',
        'rpt_openVsResolvedDesc': 'Bandingkan tiket baru terhadap throughput penyelesaian.',
        'rpt_resolutionTrend': 'Tren Waktu Resolusi',
        'rpt_resolutionTrendDesc': 'Rata-rata waktu resolusi dalam jam per hari.',
        'rpt_slaOverview': 'Ringkasan SLA',
        'rpt_compliance': 'Kepatuhan',
        'rpt_withinSla': 'Dalam SLA',
        'rpt_breached': 'Dilanggar',
        'rpt_slaTrend': 'Tren Kepatuhan SLA',
        'rpt_slaTrendDesc': 'Tingkat kepatuhan SLA harian dari waktu ke waktu.',
        'rpt_techPerformance': 'Kinerja Teknisi',
        'rpt_techPerformanceDesc': 'Rincian beban kerja per teknisi.',
        'rpt_activityHeatmap': 'Peta Panas Aktivitas',
        'rpt_activityHeatmapDesc': 'Pola pembuatan tiket berdasarkan hari dan jam.',
        'rpt_less': 'Sedikit',
        'rpt_more': 'Banyak',
        'rpt_lifecycle': 'Corong Siklus Hidup Tiket',
        'rpt_lifecycleDesc': 'Alur dari pembuatan hingga penyelesaian.',
        'rpt_reopenedAnalytics': 'Tiket Dibuka Kembali',
        'rpt_reopenedCount': 'Dibuka Kembali',
        'rpt_reopenRate': 'Tingkat Pembukaan Kembali',
        'rpt_prevPeriod': 'Periode Sblm.',
        'rpt_reopenedInsight': 'Tingkat pembukaan kembali yang tinggi dapat mengindikasikan resolusi awal yang tidak tuntas atau definisi masalah yang kurang jelas.',
        'rpt_avgRating': 'Rata-rata Penilaian',
        'rpt_ratings': 'penilaian',
        'rpt_avgHours': 'Rata-rata Jam',
        'rpt_export': 'Ekspor',
        'rpt_today': 'Hari Ini',
        'rpt_7d': '7 Hari',
        'rpt_30d': '30 Hari',
        'rpt_90d': '90 Hari',

        // Ticket Detail
        'td_description': 'Deskripsi',
        'td_solutionNotes': 'Catatan Solusi',
        'td_attachments': 'Lampiran',
        'td_activity': 'Aktivitas',
        'td_noActivity': 'Belum ada aktivitas.',
        'td_writeComment': 'Tulis komentar...',
        'td_writeCommentAdmin': 'Tulis komentar atau catatan internal...',
        'td_internalNote': 'Catatan internal',
        'td_internalNoteDesc': 'Catatan internal (tidak terlihat oleh pengguna)',
        'td_postComment': 'Kirim Komentar',
        'td_post': 'Kirim',
        'td_details': 'Detail',
        'td_requester': 'Pemohon',
        'td_assignedTo': 'Ditugaskan Kepada',
        'td_unassigned': 'Belum Ditugaskan',
        'td_created': 'Dibuat',
        'td_estimatedResolution': 'Estimasi Penyelesaian',
        'td_slaDeadline': 'Batas Waktu SLA',
        'td_closed': 'Ditutup',
        'td_yourFeedback': 'Umpan Balik Anda',
        'td_rateExperience': 'Beri penilaian pengalaman Anda',
        'td_rateDesc': 'Seberapa puas Anda dengan penyelesaian tiket ini?',
        'td_additionalFeedback': 'Umpan balik tambahan? (Opsional)',
        'td_submitFeedback': 'Kirim Umpan Balik',
        'td_issueNotResolved': 'Masalah belum selesai?',
        'td_issueNotResolvedDesc': 'Jika Anda masih mengalami masalah yang sama, Anda dapat membuka kembali tiket ini.',
        'td_reopenTicket': 'Buka Kembali Tiket',
        'td_files': 'berkas',
        'td_internal': 'Internal',
        'td_assignedToBy': 'Ditugaskan kepada',
        'td_by': 'oleh',
        'td_updateStatus': 'Perbarui Status',
        'td_addResolutionDetails': 'Tambahkan detail penyelesaian...',
        'td_assignTicket': 'Tugaskan Tiket',
        'td_assignTo': 'Tugaskan Kepada',
        'td_selectStaff': 'Pilih anggota staf',
        'td_assignmentNotes': 'Catatan (opsional)',
        'td_assignmentNotesPlaceholder': 'Catatan penugasan...',
        'td_assign': 'Tugaskan',
        'td_insertTemplate': 'Sisipkan templat...',
        'td_userSatisfaction': 'Kepuasan Pengguna',
        'td_name': 'Nama',

        // Notification Templates
        'nt_templates': 'Templat Notifikasi',
        'nt_templatesDesc': 'Kelola templat notifikasi yang dapat digunakan kembali untuk siaran dan otomatisasi.',
        'nt_newTemplate': 'Templat Baru',
        'nt_searchTemplates': 'Cari templat...',
        'nt_noTemplatesYet': 'Belum ada templat yang dibuat.',
        'nt_noMatchingTemplates': 'Tidak ada templat yang cocok.',
        'nt_createFirstTemplate': 'Buat templat pertama Anda',
        'nt_templatePreview': 'Pratinjau Templat',
        'nt_templateName': 'Nama Templat',
        'nt_subject': 'Subjek',
        'nt_content': 'Konten',
        'nt_variables': 'Variabel',
        'nt_preview': 'Pratinjau',
        'nt_confirmDelete': 'Apakah Anda yakin ingin menghapus templat ini?',
        'nt_deactivate': 'Nonaktifkan',
        'nt_activate': 'Aktifkan',

        // Notification Automation
        'na_automation': 'Otomatisasi Notifikasi',
        'na_automationDesc': 'Konfigurasi aturan notifikasi otomatis berdasarkan peristiwa sistem.',
        'na_newRule': 'Aturan Baru',
        'na_searchRules': 'Cari aturan...',
        'na_noRulesYet': 'Belum ada aturan otomatisasi.',
        'na_noMatchingRules': 'Tidak ada aturan yang cocok.',
        'na_createFirstRule': 'Buat aturan otomatisasi pertama Anda',
        'na_totalRules': 'Total Aturan',
        'na_confirmDelete': 'Apakah Anda yakin ingin menghapus aturan otomatisasi ini?',
        'na_createRuleDesc': 'Tentukan peristiwa pemicu dan hubungkan ke templat notifikasi.',
        'na_ruleName': 'Nama Aturan',
        'na_ruleNamePlaceholder': 'mis. Notifikasi saat tiket dibuat',
        'na_triggerEvent': 'Peristiwa Pemicu',
        'na_selectEvent': 'Pilih peristiwa pemicu...',
        'na_template': 'Templat Notifikasi',
        'na_selectTemplate': 'Pilih templat...',
        'na_actionConfig': 'Konfigurasi Aksi',
        'na_inAppNotification': 'Notifikasi Dalam Aplikasi',
        'na_inAppDesc': 'Tampilkan notifikasi di panel notifikasi pengguna.',
        'na_emailNotification': 'Notifikasi Email',
        'na_emailDesc': 'Kirim email ke pengguna terkait.',
        'na_activeOnCreateDesc': 'Aturan akan langsung mulai memproses peristiwa.',
        'na_createRule': 'Buat Aturan',

        // Template Create
        'nt_createTemplateDesc': 'Buat templat notifikasi yang dapat digunakan kembali dengan variabel dinamis.',
        'nt_templateNamePlaceholder': 'mis. Pembaruan Status Tiket',
        'nt_subjectPlaceholder': 'mis. Tiket #{{ticket_number}} Anda telah diperbarui',
        'nt_contentPlaceholder': 'Tulis konten notifikasi di sini. Gunakan sintaks {{variabel}} untuk nilai dinamis.',
        'nt_variablesHint': 'Tentukan variabel yang dapat digunakan di subjek dan konten. Klik variabel untuk menyisipkannya ke konten.',
        'nt_addVariablePlaceholder': 'Nama variabel (mis. ticket_number)',
        'nt_clickToInsert': 'Klik untuk menyisipkan ke konten',
        'nt_activeOnCreate': 'Aktif saat pembuatan',
        'nt_activeOnCreateDesc': 'Templat akan segera tersedia untuk digunakan.',
        'nt_createTemplate': 'Buat Templat',

        // User Notifications Page
        'nf_subtitle': 'Tetap terbarui dengan aktivitas tiket dan pemberitahuan sistem.',
        'nf_all': 'Semua',
        'nf_unread': 'Belum Dibaca',
        'nf_read': 'Sudah Dibaca',
        'nf_clearRead': 'Hapus Dibaca',
        'nf_totalNotifications': 'Total',
        'nf_today': 'Hari Ini',
        'nf_details': 'Detail',
        'nf_message': 'Pesan',
        'nf_assignedTo': 'Ditugaskan Ke',
        'nf_time': 'Waktu',
        'nf_viewTicket': 'Lihat Tiket',
        'nf_total': 'total',
        'nf_emptyDesc': 'Saat Anda menerima notifikasi tentang pembaruan tiket, mereka akan muncul di sini.',
        'nf_confirmClearRead': 'Apakah Anda yakin ingin menghapus semua notifikasi yang sudah dibaca?',

        // Admin Notification Dashboard
        'nda_title': 'Pusat Operasi Notifikasi',
        'nda_subtitle': 'Kelola siaran, templat, otomatisasi, dan pantau notifikasi sistem.',
        'nda_overviewDesc': 'Dasbor & Metrik',
        'nda_broadcastsDesc': 'Kirim & kelola',
        'nda_rulesActive': 'aturan aktif',
        'nda_systemNotifs': 'Notif Sistem',
        'nda_recentSystemNotifs': 'Notifikasi Sistem Terbaru',
        'nda_recentSystemNotifsDesc': 'Notifikasi terbaru di semua pengguna.',
        'nda_noSystemNotifs': 'Belum ada notifikasi sistem.',
        'nda_broadcastsTableDesc': '5 pesan siaran terakhir.',
        'nda_by': 'oleh',
        'nda_automationRules': 'Aturan Otomatisasi',
        'nda_monthlyQuota': 'Kuota Bulanan',
        'nda_draft': 'Draf',
        'nda_processing': 'Memproses',
        'nda_info': 'Info',
        'nda_success': 'Sukses',
        'nda_danger': 'Berbahaya',
    }
};

export function LanguageProvider({ children }) {
    const [language, setLanguage] = useState('en');

    useEffect(() => {
        const savedLang = localStorage.getItem('app_language');
        if (savedLang && (savedLang === 'en' || savedLang === 'id')) {
            setLanguage(savedLang);
        }
    }, []);

    const changeLanguage = (lang) => {
        setLanguage(lang);
        localStorage.setItem('app_language', lang);
    };

    const t = (key) => {
        return translations[language][key] || translations['en'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    return useContext(LanguageContext);
}
