import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
    en: {
        // General
        'dashboard': 'Dashboard',
        'tickets': 'Tickets',
        'settings': 'Settings',
        'profile': 'Profile',
        'logout': 'Logout',
        'cancel': 'Cancel',
        'confirm': 'Confirm',
        'save': 'Save Changes',
        'edit': 'Edit',
        'search': 'Search...',
        'actions': 'Actions',
        
        // Auth
        'signIn': 'Sign In',
        'createAccount': 'Create Account',
        'email': 'Email Address',
        'password': 'Password',
        'rememberMe': 'Remember me',
        'forgotPassword': 'Forgot Password?',
        'noAccount': "Don't have an account?",
        'registerHere': 'Register',
        'enterCredentials': 'Enter your credentials to access the system.',
        'registerDesc': 'Register to submit IT support requests.',
        
        // TopBar / Profile Dropdown
        'editProfile': 'Edit Profile',
        'language': 'English',
        'logoutConfirmTitle': 'Confirm Logout',
        'logoutConfirmDesc': 'Are you sure you want to log out of your account? You will need to sign in again to access your tickets.',
        'loggingOut': 'Logging out...',

        // Sidebar
        'myTickets': 'My Tickets',
        'createTicket': 'Create Ticket',
        'reports': 'Reports',
        'broadcast': 'Broadcast',
        'adminDashboard': 'Admin Dashboard',
        'auditLog': 'Audit Log',
        'users': 'Users',
        
        // Dashboard
        'totalTickets': 'Total Tickets',
        'open': 'Open',
        'inProgress': 'In Progress',
        'closed': 'Closed',
        'urgent': 'Urgent',
        'unassigned': 'Unassigned',
        'recentTickets': 'Recent Tickets',
        'viewAll': 'View All',
        'welcomeBack': 'Welcome back',
        'quickActions': 'Quick Actions',
        'priorityQueue': 'Priority Queue',
        'highPriority': 'High priority and unassigned tickets',
        'allClear': 'All clear',
        'noUrgent': 'No urgent or unassigned tickets require immediate attention.',
        'recentActivity': 'Recent Activity',
        'systemActions': 'System actions and updates',
        'noRecentActivity': 'No recent activity',
        'systemEventsAppear': 'System events will appear here.',
        'status': 'Status',
        'priority': 'Priority',
        'ticketId': 'Ticket ID',
        'title': 'Title',
        'date': 'Date',
        'admin': 'Admin',
        'userManagement': 'User Management',
        'manageUsersDesc': 'Manage user accounts and roles.',
        'user': 'User',
        'department': 'Department',
        'role': 'Role',
        'lastLogin': 'Last Login',
        'joined': 'Joined',
        'never': 'Never',
        'noUsersFound': 'No users found.',
        'showing': 'Showing',
        'of': 'of',
        'searchUsers': 'Search name, email, or department...',

        // Profile Page
        'profileSettings': 'Profile Settings',
        'profileSettingsDesc': 'Manage your account details and preferences.',
        'personalInfo': 'Personal Information',
        'personalInfoDesc': 'Update your basic profile details.',
        'fullName': 'Full Name',
        'changePhoto': 'Change Photo',
        'uploadPhoto': 'Upload Photo',
        'cropPhoto': 'Crop your photo',
        'zoom': 'Zoom',
        'security': 'Security',
        'securityDesc': 'Manage your password and security settings.',
        'currentPassword': 'Current Password',
        'newPassword': 'New Password',
        'confirmPassword': 'Confirm Password',
        'updatePassword': 'Update Password',
        'saveChanges': 'Save Changes',
        'saving': 'Saving...',
        
        // Notifications
        'stayUpdated': 'Stay updated on your ticket activity.',
        'markAllAsRead': 'Mark all as read',
        'ticket': 'Ticket',
        'markRead': 'Mark read',
        'page': 'Page',
        'noNotifications': 'No notifications',
        'allCaughtUp': 'You are all caught up.',
        'allTickets': 'All Tickets',
        'manageAllTickets': 'Manage all support tickets across the organization.',
        'filters': 'Filters',
        'searchPlaceholder': 'Search ID, title, or requester...',
        'allStatus': 'All Status',
        'allPriority': 'All Priority',
        'allAssignee': 'All Assignee',
        'exportCsv': 'Export CSV',
        'id': 'ID',
        'requester': 'Requester',
        'category': 'Category',
        'assigned': 'Assigned',
        'noTicketsFound': 'No tickets found',
        'adjustFilters': 'Try adjusting your filters.',
        'systemReports': 'System Reports',
        'reportsDesc': 'Analytics and performance metrics.',
        'filter': 'Filter',
        'closedTickets': 'Closed Tickets',
        'resolutionRate': 'Resolution Rate',
        'avgResolution': 'Avg. Resolution (Days)',
        'ticketsByStatus': 'Tickets by Status',
        'ticketsByPriority': 'Tickets by Priority',
        'ticketsByCategory': 'Tickets by Category',
        'ticketVolumeTrend': 'Ticket Volume Trend',
        'noData': 'No data available.',
        'noTicketData': 'No ticket data for this period.',
        'auditLogDesc': 'System activity history and audit trail.',
        'allActions': 'All Actions',
        'searchDesc': 'Search description...',
        'action': 'Action',
        'description': 'Description',
        'ip': 'IP',
        'noAuditLogs': 'No audit logs found.',
        'systemSettings': 'System Settings',
        'settingsDesc': 'Configure system parameters and ticket categories.',
        'configuration': 'Configuration',
        'ticketCategories': 'Ticket Categories',
        'cannedResponses': 'Canned Responses',
        'addCategory': 'Add Ticket Category',
        'addCategoryDesc': 'Create a new category for support tickets.',
        'categoryName': 'Category Name',
        'categoryDesc': 'Description (Optional)',
        'briefDesc': 'Brief description of this category',
        'manageCategories': 'Manage Categories',
        'manageCategoriesDesc': 'Enable or disable categories for new tickets.',
        'name': 'Name',
        'disable': 'Disable',
        'enable': 'Enable',
        'noCategories': 'No categories found.',
        'addMacro': 'Add Canned Response',
        'addMacroDesc': 'Create reply templates for fast responses.',
        'templateTitle': 'Template Title',
        'responseBody': 'Response Body',
        'writeTemplate': 'Write the template content here...',
        'addTemplate': 'Add Template',
        'manageMacros': 'Manage Canned Responses',
        'manageMacrosDesc': 'Enable or disable templates.',
        'noTemplates': 'No templates found.',
        
        // Profile additional
        'phoneNumber': 'Phone Number',
        'min8chars': 'Minimum 8 characters',

        // Broadcast
        'broadcastNotification': 'Broadcast Notification',
        'broadcastDesc': 'Send system alerts or messages to users.',
        'messageContent': '1. Message Content',
        'notificationTitle': 'Notification Title',
        'egMaintenance': 'e.g. System Maintenance',
        'messageLabel': 'Message',
        'enterDetails': 'Enter the notification details...',
        'typeLabel': 'Type',
        'infoBlue': 'Info (Blue)',
        'successGreen': 'Success (Green)',
        'warningYellow': 'Warning (Yellow)',
        'errorRed': 'Error (Red)',
        'targetAudience': '2. Target Audience',
        'allUsers': 'All Users',
        'everyoneInSystem': 'Everyone in system',
        'byDepartment': 'By Department',
        'specificDepartment': 'Specific department',
        'specificUsers': 'Specific Users',
        'selectIndividuals': 'Select individuals',
        'selectDepartment': 'Select Department',
        'selectADepartment': 'Select a department...',
        'usersSelected': 'user(s) selected',
        'sendBroadcast': 'Broadcast Notification',

        // Profile Extended
        'profileInformation': 'Profile Information',
        'preferences': 'Preferences',
        'activity': 'Activity Log',
        'languagePref': 'Language Preference',
        'notificationPref': 'Notification Preference',
        'selectLanguage': 'Select Language',
        'english': 'English',
        'indonesian': 'Indonesian',
        'emailNotifications': 'Email Notifications',
        'appNotifications': 'In-App Notifications',
        'receiveEmailUpdates': 'Receive updates about tickets via email',
        'receiveAppUpdates': 'Receive system notifications in the app',
        'auditHistory': 'Audit History',
        'noActivityLogs': 'No activity logs found.',
        'accountSummary': 'Account Summary',
        'roleLabel': 'Role',
        'departmentLabel': 'Department',
        'joinedLabel': 'Joined',
        'lastLoginLabel': 'Last Login',
        'removePhoto': 'Remove Photo',
        'uploading': 'Uploading...',
        'removing': 'Removing...',
        'cancelCrop': 'Cancel',
        'applyCrop': 'Apply',
        'cropPhoto': 'Crop Photo',
        'zoom': 'Zoom',

        // Ticket Create/Index (User)
        'createNewTicket': 'Create New Ticket',
        'createTicketDesc': 'Describe your issue and we will assist you as soon as possible.',
        'titleHelpText': 'Briefly describe the issue.',
        'titlePlaceholder': 'e.g. Printer not working in Room 204',
        'selectCategory': 'Select category',
        'low': 'Low',
        'medium': 'Medium',
        'high': 'High',
        'critical': 'Critical',
        'descriptionPlaceholder': 'Provide detailed information including steps to reproduce.',
        'attachmentsOptional': 'Attachments (optional)',
        'attachmentHint': 'Max 5 files, 10MB each. Supported: images, PDF, Office documents, markdown, ZIP.',
        'submitTicket': 'Submit Ticket',
        'trackTicketsDesc': 'Track and manage your support requests.',
        'newTicket': 'New Ticket',
        'searchByIdOrTitle': 'Search by ID or title...',
        'reopened': 'Reopened',
        'createFirstTicket': 'Create your first ticket to get started.',
        'notifications': 'Notifications',
    },
    id: {
        // General
        'dashboard': 'Beranda',
        'tickets': 'Tiket',
        'settings': 'Pengaturan',
        'profile': 'Profil',
        'logout': 'Keluar',
        'cancel': 'Batal',
        'confirm': 'Konfirmasi',
        'save': 'Simpan Perubahan',
        'edit': 'Ubah',
        'search': 'Cari...',
        'actions': 'Aksi',
        
        // Auth
        'signIn': 'Masuk',
        'createAccount': 'Buat Akun',
        'email': 'Alamat Email',
        'password': 'Kata Sandi',
        'rememberMe': 'Ingat saya',
        'forgotPassword': 'Lupa Kata Sandi?',
        'noAccount': "Belum memiliki akun?",
        'registerHere': 'Daftar',
        'enterCredentials': 'Masukkan kredensial Anda untuk mengakses sistem.',
        'registerDesc': 'Daftar untuk mengirimkan permintaan dukungan IT.',
        
        // TopBar / Profile Dropdown
        'editProfile': 'Ubah Profil',
        'language': 'Bahasa Indonesia',
        'logoutConfirmTitle': 'Konfirmasi Keluar',
        'logoutConfirmDesc': 'Apakah Anda yakin ingin keluar dari akun Anda? Anda harus masuk kembali untuk mengakses tiket Anda.',
        'loggingOut': 'Keluar...',

        // Sidebar
        'myTickets': 'Tiket Saya',
        'createTicket': 'Buat Tiket',
        'reports': 'Laporan',
        'broadcast': 'Notifikasi',
        'adminDashboard': 'Beranda Admin',
        'auditLog': 'Log Audit',
        'users': 'Pengguna',
        'notifications': 'Notifikasi',
        
        // Dashboard
        'totalTickets': 'Total Tiket',
        'open': 'Buka',
        'inProgress': 'Diproses',
        'closed': 'Selesai',
        'urgent': 'Mendesak',
        'unassigned': 'Belum Ditugaskan',
        'recentTickets': 'Tiket Terbaru',
        'viewAll': 'Lihat Semua',
        'welcomeBack': 'Selamat datang kembali',
        'quickActions': 'Aksi Cepat',
        'priorityQueue': 'Antrean Prioritas',
        'highPriority': 'Tiket prioritas tinggi dan belum ditugaskan',
        'allClear': 'Semua aman',
        'noUrgent': 'Tidak ada tiket mendesak yang memerlukan perhatian segera.',
        'recentActivity': 'Aktivitas Terbaru',
        'systemActions': 'Tindakan dan pembaruan sistem',
        'noRecentActivity': 'Tidak ada aktivitas terbaru',
        'systemEventsAppear': 'Peristiwa sistem akan muncul di sini.',
        'status': 'Status',
        'priority': 'Prioritas',
        'ticketId': 'ID Tiket',
        'title': 'Judul',
        'date': 'Tanggal',
        'admin': 'Admin',
        'userManagement': 'Manajemen Pengguna',
        'manageUsersDesc': 'Kelola akun pengguna dan peran.',
        'user': 'Pengguna',
        'department': 'Departemen',
        'role': 'Peran',
        'lastLogin': 'Terakhir Masuk',
        'joined': 'Bergabung',
        'never': 'Belum Pernah',
        'noUsersFound': 'Tidak ada pengguna yang ditemukan.',
        'showing': 'Menampilkan',
        'of': 'dari',
        'searchUsers': 'Cari nama, email, atau departemen...',

        // Profile Page
        'profileSettings': 'Pengaturan Profil',
        'profileSettingsDesc': 'Kelola detail dan preferensi akun Anda.',
        'personalInfo': 'Informasi Pribadi',
        'personalInfoDesc': 'Perbarui detail profil dasar Anda.',
        'fullName': 'Nama Lengkap',
        'changePhoto': 'Ubah Foto',
        'uploadPhoto': 'Unggah Foto',
        'cropPhoto': 'Potong foto Anda',
        'zoom': 'Perbesar',
        'security': 'Keamanan',
        'securityDesc': 'Kelola kata sandi dan pengaturan keamanan Anda.',
        'currentPassword': 'Kata Sandi Saat Ini',
        'newPassword': 'Kata Sandi Baru',
        'confirmPassword': 'Konfirmasi Kata Sandi',
        'updatePassword': 'Perbarui Kata Sandi',
        'saveChanges': 'Simpan Perubahan',
        'saving': 'Menyimpan...',
        
        // Notifications
        'stayUpdated': 'Tetap perbarui aktivitas tiket Anda.',
        'markAllAsRead': 'Tandai semua telah dibaca',
        'ticket': 'Tiket',
        'markRead': 'Tandai dibaca',
        'page': 'Halaman',
        'noNotifications': 'Tidak ada notifikasi',
        'allCaughtUp': 'Semua sudah beres.',
        'allTickets': 'Semua Tiket',
        'manageAllTickets': 'Kelola semua tiket dukungan di seluruh organisasi.',
        'filters': 'Filter',
        'searchPlaceholder': 'Cari ID, judul, atau pemohon...',
        'allStatus': 'Semua Status',
        'allPriority': 'Semua Prioritas',
        'allAssignee': 'Semua Petugas',
        'exportCsv': 'Ekspor CSV',
        'id': 'ID',
        'requester': 'Pemohon',
        'category': 'Kategori',
        'assigned': 'Ditugaskan',
        'noTicketsFound': 'Tidak ada tiket ditemukan',
        'adjustFilters': 'Coba sesuaikan filter Anda.',
        'systemReports': 'Laporan Sistem',
        'reportsDesc': 'Metrik analitik dan kinerja.',
        'filter': 'Filter',
        'closedTickets': 'Tiket Selesai',
        'resolutionRate': 'Tingkat Penyelesaian',
        'avgResolution': 'Rata-rata Penyelesaian (Hari)',
        'ticketsByStatus': 'Tiket berdasarkan Status',
        'ticketsByPriority': 'Tiket berdasarkan Prioritas',
        'ticketsByCategory': 'Tiket berdasarkan Kategori',
        'ticketVolumeTrend': 'Tren Volume Tiket',
        'noData': 'Tidak ada data tersedia.',
        'noTicketData': 'Tidak ada data tiket untuk periode ini.',
        'auditLogDesc': 'Riwayat aktivitas sistem dan jejak audit.',
        'allActions': 'Semua Aksi',
        'searchDesc': 'Cari deskripsi...',
        'action': 'Aksi',
        'description': 'Deskripsi',
        'ip': 'IP',
        'noAuditLogs': 'Tidak ada log audit ditemukan.',
        'systemSettings': 'Pengaturan Sistem',
        'settingsDesc': 'Konfigurasi parameter sistem dan kategori tiket.',
        'configuration': 'Konfigurasi',
        'ticketCategories': 'Kategori Tiket',
        'cannedResponses': 'Tanggapan Cepat',
        'addCategory': 'Tambah Kategori Tiket',
        'addCategoryDesc': 'Buat kategori baru untuk tiket dukungan.',
        'categoryName': 'Nama Kategori',
        'categoryDesc': 'Deskripsi (Opsional)',
        'briefDesc': 'Deskripsi singkat tentang kategori ini',
        'manageCategories': 'Kelola Kategori',
        'manageCategoriesDesc': 'Aktifkan atau nonaktifkan kategori untuk tiket baru.',
        'name': 'Nama',
        'disable': 'Nonaktifkan',
        'enable': 'Aktifkan',
        'noCategories': 'Tidak ada kategori ditemukan.',
        'addMacro': 'Tambah Tanggapan Cepat',
        'addMacroDesc': 'Buat templat balasan untuk tanggapan cepat.',
        'templateTitle': 'Judul Templat',
        'responseBody': 'Isi Tanggapan',
        'writeTemplate': 'Tulis konten templat di sini...',
        'addTemplate': 'Tambah Templat',
        'manageMacros': 'Kelola Tanggapan Cepat',
        'manageMacrosDesc': 'Aktifkan atau nonaktifkan templat.',
        'noTemplates': 'Tidak ada templat ditemukan.',
        
        // Profile additional
        'phoneNumber': 'Nomor Telepon',
        'min8chars': 'Minimal 8 karakter',

        // Broadcast
        'broadcastNotification': 'Notifikasi Siaran',
        'broadcastDesc': 'Kirim peringatan sistem atau pesan ke pengguna.',
        'messageContent': '1. Isi Pesan',
        'notificationTitle': 'Judul Notifikasi',
        'egMaintenance': 'mis. Pemeliharaan Sistem',
        'messageLabel': 'Pesan',
        'enterDetails': 'Masukkan detail notifikasi...',
        'typeLabel': 'Tipe',
        'infoBlue': 'Info (Biru)',
        'successGreen': 'Sukses (Hijau)',
        'warningYellow': 'Peringatan (Kuning)',
        'errorRed': 'Kesalahan (Merah)',
        'targetAudience': '2. Target Pengguna',
        'allUsers': 'Semua Pengguna',
        'everyoneInSystem': 'Semua orang dalam sistem',
        'byDepartment': 'Berdasarkan Departemen',
        'specificDepartment': 'Departemen tertentu',
        'specificUsers': 'Pengguna Tertentu',
        'selectIndividuals': 'Pilih individu',
        'selectDepartment': 'Pilih Departemen',
        'selectADepartment': 'Pilih departemen...',
        'usersSelected': 'pengguna dipilih',
        'sendBroadcast': 'Kirim Notifikasi',

        // Profile Extended
        'profileInformation': 'Informasi Profil',
        'preferences': 'Preferensi',
        'activity': 'Log Aktivitas',
        'languagePref': 'Preferensi Bahasa',
        'notificationPref': 'Preferensi Notifikasi',
        'selectLanguage': 'Pilih Bahasa',
        'english': 'Bahasa Inggris',
        'indonesian': 'Bahasa Indonesia',
        'emailNotifications': 'Notifikasi Email',
        'appNotifications': 'Notifikasi Dalam Aplikasi',
        'receiveEmailUpdates': 'Terima pembaruan tentang tiket via email',
        'receiveAppUpdates': 'Terima notifikasi sistem di aplikasi',
        'auditHistory': 'Riwayat Audit',
        'noActivityLogs': 'Tidak ada log aktivitas.',
        'accountSummary': 'Ringkasan Akun',
        'roleLabel': 'Peran',
        'departmentLabel': 'Departemen',
        'joinedLabel': 'Bergabung',
        'lastLoginLabel': 'Terakhir Masuk',
        'removePhoto': 'Hapus Foto',
        'uploading': 'Mengunggah...',
        'removing': 'Menghapus...',
        'cancelCrop': 'Batal',
        'applyCrop': 'Terapkan',
        'cropPhoto': 'Potong Foto',
        'zoom': 'Perbesar',

        // Ticket Create/Index (User)
        'createNewTicket': 'Buat Tiket Baru',
        'createTicketDesc': 'Jelaskan masalah Anda dan kami akan membantu secepatnya.',
        'titleHelpText': 'Jelaskan masalah secara singkat.',
        'titlePlaceholder': 'mis. Printer tidak berfungsi di Ruang 204',
        'selectCategory': 'Pilih kategori',
        'low': 'Rendah',
        'medium': 'Sedang',
        'high': 'Tinggi',
        'critical': 'Kritis',
        'descriptionPlaceholder': 'Berikan informasi lengkap termasuk langkah-langkah untuk mereproduksi masalah.',
        'attachmentsOptional': 'Lampiran (opsional)',
        'attachmentHint': 'Maks 5 berkas, 10MB per berkas. Didukung: gambar, PDF, dokumen Office, markdown, ZIP.',
        'submitTicket': 'Kirim Tiket',
        'trackTicketsDesc': 'Lacak dan kelola permintaan dukungan Anda.',
        'newTicket': 'Tiket Baru',
        'searchByIdOrTitle': 'Cari berdasarkan ID atau judul...',
        'reopened': 'Dibuka Kembali',
        'createFirstTicket': 'Buat tiket pertama Anda untuk memulai.',
        'notifications': 'Notifikasi',
    }
};

export function LanguageProvider({ children }) {
    const [language, setLanguage] = useState('en');

    useEffect(() => {
        const savedLang = localStorage.getItem('app_language');
        if (savedLang && (savedLang === 'en' || savedLang === 'id')) {
            setLanguage(savedLang);
        }
    }, []);

    const changeLanguage = (lang) => {
        setLanguage(lang);
        localStorage.setItem('app_language', lang);
    };

    const t = (key) => {
        return translations[language][key] || translations['en'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    return useContext(LanguageContext);
}
