import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
    en: {
        // General
        'dashboard': 'Dashboard',
        'tickets': 'Tickets',
        'settings': 'Settings',
        'profile': 'Profile',
        'logout': 'Logout',
        'cancel': 'Cancel',
        'confirm': 'Confirm',
        'save': 'Save Changes',
        'edit': 'Edit',
        'search': 'Search...',
        'actions': 'Actions',
        'delete': 'Delete',
        'active': 'Active',
        'inactive': 'Inactive',
        'notifications': 'Notifications',
        'ticket': 'Ticket',
        'allTickets': 'All Tickets',
        'department': 'Department',
        'noData': 'No data available',
        
        // Auth
        'signIn': 'Sign In',
        'createAccount': 'Create Account',
        'email': 'Email Address',
        'password': 'Password',
        'rememberMe': 'Remember me',
        'forgotPassword': 'Forgot Password?',
        'noAccount': "Don't have an account?",
        'registerHere': 'Register',
        'enterCredentials': 'Enter your credentials to access the system.',
        'registerDesc': 'Register to submit IT support requests.',
        
        // TopBar / Profile Dropdown
        'editProfile': 'Edit Profile',
        'theme': 'Theme',
        'language': 'English',
        'logoutConfirmTitle': 'Confirm Logout',
        'logoutConfirmDesc': 'Are you sure you want to log out of your account? You will need to sign in again to access your tickets.',
        'loggingOut': 'Logging out...',

        // Sidebar
        'myTickets': 'My Tickets',
        'createTicket': 'Create Ticket',
        'reports': 'Reports',
        'broadcast': 'Broadcast',
        'adminDashboard': 'Admin Dashboard',
        'auditLog': 'Audit Log',
        'documentation': 'Documentation',
        'knowledgeBase': 'Knowledge Base',
        'users': 'Users',
        
        // Dashboard
        'totalTickets': 'Total Tickets',
        'closed': 'Closed',
        'reopened': 'Reopened',
        'inProgress': 'In Progress',
        'open': 'Open',
        'urgent': 'Urgent',
        'unassigned': 'Unassigned',
        'recentTickets': 'Recent Tickets',
        'viewAll': 'View All',
        'welcomeBack': 'Welcome back',
        'quickActions': 'Quick Actions',
        'priorityQueue': 'Priority Queue',
        'highPriority': 'High priority and unassigned tickets',
        'allClear': 'All clear',
        'noUrgent': 'No urgent or unassigned tickets require immediate attention.',
        'recentActivity': 'Recent Activity',
        'systemActions': 'System actions and updates',
        'noRecentActivity': 'No recent activity',
        'systemEventsAppear': 'System events will appear here.',
        'status': 'Status',
        'priority': 'Priority',
        'ticketId': 'Ticket ID',
        'title': 'Title',
        'date': 'Date',
        'admin': 'Admin',
        'userManagement': 'User Management',
        'manageUsersDesc': 'Manage user accounts and roles.',
        'user': 'User',
        'role': 'Role',
        'lastLogin': 'Last Login',
        'joined': 'Joined',
        'never': 'Never',
        'noUsersFound': 'No users found.',
        'showing': 'Showing',
        'of': 'of',
        'searchUsers': 'Search name, email, or department...',

        // Profile Page
        'profileSettings': 'Profile Settings',
        'profileSettingsDesc': 'Manage your account details and preferences.',
        'personalInfo': 'Personal Information',
        'personalInfoDesc': 'Update your basic profile details.',
        'fullName': 'Full Name',
        'changePhoto': 'Change Photo',
        'uploadPhoto': 'Upload Photo',
        'cropPhoto': 'Crop your photo',
        'zoom': 'Zoom',
        'security': 'Security',
        'securityDesc': 'Manage your password and security settings.',
        'currentPassword': 'Current Password',
        'newPassword': 'New Password',
        'confirmPassword': 'Confirm Password',
        'updatePassword': 'Update Password',
        'saveChanges': 'Save Changes',
        'saving': 'Saving...',
        
        // Notifications
        'stayUpdated': 'Stay updated on your ticket activity.',
        'markAllAsRead': 'Mark all as read',
        'markRead': 'Mark read',
        'page': 'Page',
        'noNotifications': 'No notifications',
        'allCaughtUp': 'You are all caught up.',
        'manageAllTickets': 'Manage all support tickets across the organization.',
        'filters': 'Filters',
        'searchPlaceholder': 'Search ID, title, or requester...',
        'allStatus': 'All Status',
        'allPriority': 'All Priority',
        'allAssignee': 'All Assignee',
        'unassigned': 'Unassigned',
        'low': 'Low',
        'medium': 'Medium',
        'high': 'High',
        'critical': 'Critical',
        'exportCsv': 'Export CSV',
        'id': 'ID',
        'requester': 'Requester',
        'category': 'Category',
        'assigned': 'Assigned',
        'noTicketsFound': 'No tickets found',
        'adjustFilters': 'Try adjusting your filters.',
        'systemReports': 'System Reports',
        'reportsDesc': 'Analytics and performance metrics.',
        'filter': 'Filter',
        'closedTickets': 'Closed Tickets',
        'resolutionRate': 'Resolution Rate',
        'avgResolution': 'Avg. Resolution (Days)',
        'ticketsByStatus': 'Tickets by Status',
        'ticketsByPriority': 'Tickets by Priority',
        'ticketsByCategory': 'Tickets by Category',
        'ticketVolumeTrend': 'Ticket Volume Trend',
        'noTicketData': 'No ticket data for this period.',
        'auditLogDesc': 'System activity history and audit trail.',
        'allActions': 'All Actions',
        'searchDesc': 'Search description...',
        'action': 'Action',
        'description': 'Description',
        'ip': 'IP',
        'noAuditLogs': 'No audit logs found.',
        'systemSettings': 'System Settings',
        'settingsDesc': 'Configure system parameters and ticket categories.',
        'configuration': 'Configuration',
        'ticketCategories': 'Ticket Categories',
        'cannedResponses': 'Canned Responses',
        'addCategory': 'Add Ticket Category',
        'addCategoryDesc': 'Create a new category for support tickets.',
        'categoryName': 'Category Name',
        'categoryDesc': 'Description (Optional)',
        'briefDesc': 'Brief description of this category',
        'manageCategories': 'Manage Categories',
        'manageCategoriesDesc': 'Enable or disable categories for new tickets.',
        'name': 'Name',
        'disable': 'Disable',
        'enable': 'Enable',
        'noCategories': 'No categories found.',
        'addMacro': 'Add Canned Response',
        'addMacroDesc': 'Create reply templates for fast responses.',
        'templateTitle': 'Template Title',
        'responseBody': 'Response Body',
        'writeTemplate': 'Write the template content here...',
        'addTemplate': 'Add Template',
        'manageMacros': 'Manage Canned Responses',
        'manageMacrosDesc': 'Enable or disable templates.',
        'noTemplates': 'No templates found.',
        
        // Profile additional
        'phoneNumber': 'Phone Number',
        'phonePlaceholder': '081234567890',
        'phoneHint': 'Numbers only, 9–15 digits.',
        'departmentAdminOnly': 'Department can only be changed by an Admin.',
        'contactAdminToChange': 'Contact administrator to change.',
        'min8chars': 'Minimum 8 characters',

        // Broadcast
        'broadcastNotification': 'Broadcast Notification',
        'broadcastDesc': 'Send system alerts or messages to users.',
        'messageContent': '1. Message Content',
        'notificationTitle': 'Notification Title',
        'egMaintenance': 'e.g. System Maintenance',
        'messageLabel': 'Message',
        'enterDetails': 'Enter the notification details...',
        'typeLabel': 'Type',
        'infoBlue': 'Info (Blue)',
        'successGreen': 'Success (Green)',
        'warningYellow': 'Warning (Yellow)',
        'errorRed': 'Error (Red)',
        'targetAudience': '2. Target Audience',
        'allUsers': 'All Users',
        'everyoneInSystem': 'Everyone in system',
        'byDepartment': 'By Department',
        'specificDepartment': 'Specific department',
        'specificUsers': 'Specific Users',
        'selectIndividuals': 'Select individuals',
        'selectDepartment': 'Select Department',
        'selectADepartment': 'Select a department...',
        'usersSelected': 'user(s) selected',
        'sendBroadcast': 'Broadcast Notification',
        'broadcastDetail': 'Broadcast detail and delivery log.',
        'broadcastContent': 'Broadcast Content',
        'creator': 'Creator',
        'sentAt': 'Sent At',
        'audience': 'Audience',
        'channel': 'Channel',
        'deliveryLog': 'Delivery Log',
        'recipients': 'recipients',
        'readAt': 'Read At',
        'delivered': 'Delivered',
        'noDeliveryLogs': 'No delivery logs available.',
        'searchUsersDot': 'Search users...',
        'confirmDeleteCategory': 'Are you sure you want to delete this category?',
        'confirmDeleteMacro': 'Are you sure you want to delete this template?',
        'td_escalation': 'Escalation',
        'td_escalated': 'Escalated',
        'td_escalationReason': 'Reason for escalation',
        'td_escalationReasonPlaceholder': 'Reason for escalation...',
        'td_escalateTicket': 'Escalate Ticket',
        'td_escalateFurther': 'Escalate Further',
        'draft': 'Draft',
        'reopened': 'Reopened',
        'open': 'Open',
        'inProgress': 'In Progress',
        'closed': 'Closed',
        'td_invalidTransition': 'Cannot perform this status change.',

        // Flash Messages
        'td_ticketCreatedSuccess': 'Ticket created successfully.',
        'td_ticketUpdatedSuccess': 'Ticket updated successfully.',
        'td_ticketReopenedSuccess': 'Ticket reopened successfully.',
        'td_ticketDeletedSuccess': 'Ticket deleted successfully.',
        'td_ticketAssignedSuccess': 'Ticket assigned successfully.',
        'td_ticketEscalatedSuccess': 'Ticket escalated successfully.',
        'td_feedbackThanks': 'Thank you for your feedback!',
        'td_rateClosedOnly': 'You can only rate closed tickets.',
        'td_commentPosted': 'Comment posted.',
        'td_profileUpdated': 'Profile updated successfully.',
        'td_passwordChanged': 'Password changed successfully.',
        'td_photoUpdated': 'Profile photo updated successfully.',
        'td_photoRemoved': 'Profile photo removed successfully.',
        'td_coverUpdated': 'Cover photo updated successfully.',
        'td_coverRemoved': 'Cover photo removed.',
        'td_preferencesUpdated': 'Preferences updated successfully.',
        'td_draftNotice': 'This ticket is currently a draft.',
        'td_draftNoticeDesc': 'Submit this ticket when you are ready to send it to the IT Support team.',
        'td_submitDraft': 'Submit Ticket',
        'td_editDraft': 'Edit Draft',
        'td_draftSubmittedSuccess': 'Draft submitted successfully.',
        'td_allNotificationsRead': 'All notifications marked as read.',
        'td_notificationDeleted': 'Notification deleted.',
        'td_readNotificationsCleared': 'Read notifications cleared.',
        'tc_addAttachments': 'Add Attachments',

        // Profile Extended
        'profileInformation': 'Profile Information',
        'preferences': 'Preferences',
        'activity': 'Activity Log',
        'languagePref': 'Language Preference',
        'notificationPref': 'Notification Preference',
        'selectLanguage': 'Select Language',
        'english': 'English',
        'indonesian': 'Indonesian',
        'emailNotifications': 'Email Notifications',
        'appNotifications': 'In-App Notifications',
        'receiveEmailUpdates': 'Receive updates about tickets via email',
        'receiveAppUpdates': 'Receive system notifications in the app',
        'auditHistory': 'Audit History',
        'noActivityLogs': 'No activity logs found.',
        'accountSummary': 'Account Summary',
        'roleLabel': 'Role',
        'departmentLabel': 'Department',
        'joinedLabel': 'Joined',
        'lastLoginLabel': 'Last Login',
        'removePhoto': 'Remove Photo',
        'uploading': 'Uploading...',
        'removing': 'Removing...',
        'cancelCrop': 'Cancel',
        'applyCrop': 'Apply',

        // Ticket Create/Index (User)
        'createNewTicket': 'Create New Ticket',
        'createTicketDesc': 'Describe your issue and we will assist you as soon as possible.',
        'titleHelpText': 'Briefly describe the issue.',
        'titlePlaceholder': 'e.g. Printer not working in Room 204',
        'selectCategory': 'Select category',
        'low': 'Low',
        'medium': 'Medium',
        'high': 'High',
        'critical': 'Critical',
        'descriptionPlaceholder': 'Provide detailed information including steps to reproduce.',
        'attachmentsOptional': 'Attachments (optional)',
        'attachmentHint': 'Max 5 files, 10MB each. Supported: images, PDF, Office documents, markdown, ZIP.',
        'submitTicket': 'Submit Ticket',
        'trackTicketsDesc': 'Track and manage your support requests.',
        'newTicket': 'New Ticket',
        'searchByIdOrTitle': 'Search by ID or title...',
        'createFirstTicket': 'Create your first ticket to get started.',

        // Notification Operations Center
        'notificationOperationsCenter': 'Notification Operations Center',
        'notificationOperationsCenterDesc': 'Manage broadcasts, templates, and automated notifications.',
        'newBroadcast': 'New Broadcast',
        'overview': 'Overview',
        'broadcasts': 'Broadcasts',
        'templates': 'Templates',
        'automation': 'Automation',
        'totalBroadcasts': 'Total Broadcasts',
        'completed': 'Completed',
        'scheduled': 'Scheduled',
        'failed': 'Failed',
        'recentBroadcasts': 'Recent Broadcasts',
        'type': 'Type',
        'noBroadcastsFound': 'No broadcasts found',
        'noBroadcastsDesc': "You haven't sent any broadcasts yet.",
        'createBroadcast': 'Create Broadcast',
        'systemCapacity': 'System Capacity',
        'monthlyQuota': 'Monthly Quota',
        'unlimited': 'Unlimited',
        'info': 'Info',
        'success': 'Success',
        'warning': 'Warning',
        'error': 'Error',
        'draft': 'Draft',
        'processing': 'Processing',

        // Reports Dashboard
        'rpt_title': 'Reporting Dashboard',
        'rpt_subtitle': 'Comprehensive analytics and performance insights.',
        'rpt_tickets': 'Tickets',
        'rpt_opened': 'Opened',
        'rpt_resolved': 'Resolved',
        'rpt_pending': 'Pending',
        'rpt_overdue': 'Overdue',
        'rpt_avgResTime': 'Avg. Resolution',
        'rpt_slaCompliance': 'SLA Compliance',
        'rpt_resolvedToday': 'Resolved Today',
        'rpt_reopened': 'Reopened',
        'rpt_satisfaction': 'Satisfaction',
        'rpt_vsPrev': 'vs previous period',
        'rpt_openVsResolved': 'Opened vs Resolved',
        'rpt_openVsResolvedDesc': 'Compare new tickets against resolved throughput.',
        'rpt_resolutionTrend': 'Resolution Time Trend',
        'rpt_resolutionTrendDesc': 'Average resolution time in hours per day.',
        'rpt_slaOverview': 'SLA Overview',
        'rpt_compliance': 'Compliance',
        'rpt_withinSla': 'Within SLA',
        'rpt_breached': 'Breached',
        'rpt_slaTrend': 'SLA Compliance Trend',
        'rpt_slaTrendDesc': 'Daily SLA compliance rate over time.',
        'rpt_techPerformance': 'Technician Performance',
        'rpt_techPerformanceDesc': 'Workload breakdown per technician.',
        'rpt_activityHeatmap': 'Activity Heatmap',
        'rpt_activityHeatmapDesc': 'Ticket creation patterns by day and hour.',
        'rpt_less': 'Less',
        'rpt_more': 'More',
        'rpt_lifecycle': 'Ticket Lifecycle Funnel',
        'rpt_lifecycleDesc': 'Flow from creation to resolution.',
        'rpt_reopenedAnalytics': 'Reopened Tickets',
        'rpt_reopenedCount': 'Reopened',
        'rpt_reopenRate': 'Reopen Rate',
        'rpt_prevPeriod': 'Prev. Period',
        'rpt_reopenedInsight': 'A high reopen rate may indicate incomplete initial resolution or unclear problem definition.',
        'rpt_avgRating': 'Average Rating',
        'rpt_ratings': 'ratings',
        'rpt_avgHours': 'Avg. Hours',
        'rpt_export': 'Export',
        'rpt_today': 'Today',
        'rpt_7d': '7 Days',
        'rpt_30d': '30 Days',
        'rpt_90d': '90 Days',

        // Ticket Detail
        'td_description': 'Description',
        'td_solutionNotes': 'Solution Notes',
        'td_attachments': 'Attachments',
        'td_activity': 'Activity',
        'td_noActivity': 'No activity yet.',
        'td_writeComment': 'Write a comment...',
        'td_writeCommentAdmin': 'Write a comment or internal note...',
        'td_internalNote': 'Internal note',
        'td_internalNoteDesc': 'Internal note (not visible to user)',
        'td_postComment': 'Post Comment',
        'td_post': 'Post',
        'td_details': 'Details',
        'td_requester': 'Requester',
        'td_assignedTo': 'Assigned To',
        'td_unassigned': 'Unassigned',
        'td_created': 'Created',
        'td_estimatedResolution': 'Estimated Resolution',
        'td_slaDeadline': 'SLA Deadline',
        'td_responseDeadline': 'Response Deadline',
        'td_firstRespondedAt': 'First Responded At',
        'td_escalationLevel': 'Escalation Level',
        'td_escalatedAt': 'Escalated At',
        'td_escalationReason': 'Escalation Reason',
        'td_escalated': 'Escalated',
        'td_escalation': 'Escalation',
        'td_escalateFurther': 'Escalate Further',
        'td_escalateTicket': 'Escalate Ticket',
        'td_escalationReasonPlaceholder': 'Reason for escalation...',
        'td_draftNotice': 'This ticket is currently a draft.',
        'td_draftNoticeDesc': 'Submit this ticket when you are ready to send it to the IT Support team.',
        'td_submitDraft': 'Submit Ticket',
        'td_closed': 'Closed',
        
        // Duplicates
        'similarTicketsFound': 'Similar Open Tickets Found',
        'similarTicketsDesc': 'Before submitting, please check if these similar tickets already address your issue:',
        'viewTicket': 'View Ticket',
        'td_yourFeedback': 'Your Feedback',
        'td_rateExperience': 'Rate your experience',
        'td_rateDesc': 'How satisfied are you with the resolution of this ticket?',
        'td_additionalFeedback': 'Any additional feedback? (Optional)',
        'td_submitFeedback': 'Submit Feedback',
        'td_issueNotResolved': 'Issue not resolved?',
        'td_issueNotResolvedDesc': 'If you are still experiencing the same issue, you can reopen this ticket.',
        'td_reopenTicket': 'Reopen Ticket',
        'td_files': 'file(s)',
        'td_internal': 'Internal',
        'td_assignedToBy': 'Assigned to',
        'td_by': 'by',
        'td_updateStatus': 'Update Status',
        'td_addResolutionDetails': 'Add resolution details...',
        'td_assignTicket': 'Assign Ticket',
        'td_assignTo': 'Assign To',
        'td_selectStaff': 'Select staff member',
        'td_assignmentNotes': 'Notes (optional)',
        'td_assignmentNotesPlaceholder': 'Assignment notes...',
        'td_assign': 'Assign',
        'td_insertTemplate': 'Insert template...',
        'td_userSatisfaction': 'User Satisfaction',
        'td_name': 'Name',

        // Notification Templates
        'nt_templates': 'Notification Templates',
        'nt_templatesDesc': 'Manage reusable notification templates for broadcasts and automation.',
        'nt_newTemplate': 'New Template',
        'nt_searchTemplates': 'Search templates...',
        'nt_noTemplatesYet': 'No templates created yet.',
        'nt_noMatchingTemplates': 'No templates match your search.',
        'nt_createFirstTemplate': 'Create your first template',
        'nt_templatePreview': 'Template Preview',
        'nt_templateName': 'Template Name',
        'nt_subject': 'Subject',
        'nt_content': 'Content',
        'nt_variables': 'Variables',
        'nt_preview': 'Preview',
        'nt_confirmDelete': 'Are you sure you want to delete this template?',
        'nt_deactivate': 'Deactivate',
        'nt_activate': 'Activate',

        // Notification Automation
        'na_automation': 'Notification Automation',
        'na_automationDesc': 'Configure automated notification rules triggered by system events.',
        'na_newRule': 'New Rule',
        'na_searchRules': 'Search rules...',
        'na_noRulesYet': 'No automation rules created yet.',
        'na_noMatchingRules': 'No rules match your search.',
        'na_createFirstRule': 'Create your first automation rule',
        'na_totalRules': 'Total Rules',
        'na_confirmDelete': 'Are you sure you want to delete this automation rule?',
        'na_createRuleDesc': 'Define a trigger event and link it to a notification template.',
        'na_ruleName': 'Rule Name',
        'na_ruleNamePlaceholder': 'e.g. Notify on ticket creation',
        'na_triggerEvent': 'Trigger Event',
        'na_selectEvent': 'Select a trigger event...',
        'na_template': 'Notification Template',
        'na_selectTemplate': 'Select a template...',
        'na_actionConfig': 'Action Configuration',
        'na_inAppNotification': 'In-App Notification',
        'na_inAppDesc': 'Show notification in the user notification panel.',
        'na_emailNotification': 'Email Notification',
        'na_emailDesc': 'Send email to the affected user.',
        'na_activeOnCreateDesc': 'Rule will start processing events immediately.',
        'na_createRule': 'Create Rule',

        // Template Create
        'nt_createTemplateDesc': 'Create a reusable notification template with dynamic variables.',
        'nt_templateNamePlaceholder': 'e.g. Ticket Status Update',
        'nt_subjectPlaceholder': 'e.g. Your ticket #{{ticket_number}} has been updated',
        'nt_contentPlaceholder': 'Write your notification content here. Use {{variable}} syntax for dynamic values.',
        'nt_variablesHint': 'Define variables that can be used in the subject and content. Click a variable to insert it into the content.',
        'nt_addVariablePlaceholder': 'Variable name (e.g. ticket_number)',
        'nt_clickToInsert': 'Click to insert into content',
        'nt_activeOnCreate': 'Active on creation',
        'nt_activeOnCreateDesc': 'Template will be immediately available for use.',
        'nt_createTemplate': 'Create Template',

        // User Notifications Page
        'nf_subtitle': 'Stay updated with your ticket activity and system alerts.',
        'nf_all': 'All',
        'nf_unread': 'Unread',
        'nf_read': 'Read',
        'nf_clearRead': 'Clear Read',
        'nf_totalNotifications': 'Total',
        'nf_today': 'Today',
        'nf_details': 'Details',
        'nf_message': 'Message',
        'nf_assignedTo': 'Assigned To',
        'nf_time': 'Time',
        'nf_viewTicket': 'View Ticket',
        'nf_total': 'total',
        'nf_emptyDesc': 'When you receive notifications about ticket updates, they will appear here.',
        'nf_confirmClearRead': 'Are you sure you want to delete all read notifications?',

        // Admin Notification Dashboard
        'nda_title': 'Notification Operations Center',
        'nda_subtitle': 'Manage broadcasts, templates, automation, and monitor system notifications.',
        'nda_overviewDesc': 'Dashboard & Metrics',
        'nda_broadcastsDesc': 'Send & manage',
        'nda_rulesActive': 'rules active',
        'nda_systemNotifs': 'System Notifs',
        'nda_recentSystemNotifs': 'Recent System Notifications',
        'nda_recentSystemNotifsDesc': 'Latest notifications across all users.',
        'nda_noSystemNotifs': 'No system notifications yet.',
        'nda_broadcastsTableDesc': 'Last 5 broadcast messages.',
        'nda_by': 'by',
        'nda_automationRules': 'Automation Rules',
        'nda_monthlyQuota': 'Monthly Quota',
        'nda_draft': 'Draft',
        'nda_processing': 'Processing',
        'nda_info': 'Info',
        'nda_success': 'Success',
        'nda_danger': 'Danger',

        // Ticket Create (New Enterprise Workflow)
        'tc_issueInfo': 'Issue Information',
        'tc_ticketClassification': 'Ticket Classification',
        'tc_issueDescription': 'Detailed Issue Description',
        'tc_smartRecommendations': 'Smart Recommendations',
        'tc_attachments': 'Attachment & Evidence',
        'tc_slaWorkflowInfo': 'SLA & Workflow Information',
        'tc_operationalGuidance': 'Operational Guidance',
        'tc_submissionConfirmation': 'Submission Confirmation',
        'tc_suggestedPriority': 'Suggested Priority',
        'tc_suggestedCategory': 'Suggested Category',
        'tc_estimatedSLA': 'Estimated SLA',
        'tc_recommendedDept': 'Recommended Department',
        'tc_issueSeverity': 'Issue Severity',
        'tc_relatedArticles': 'Related Knowledge Base Articles',
        'tc_possibleSimilarTickets': 'Possible Similar Tickets',
        'tc_deviceType': 'Device Type',
        'tc_assetNumber': 'Asset Number',
        'tc_physicalLocation': 'Physical Location',
        'tc_hardwareModel': 'Hardware Model',
        'tc_operatingSystem': 'Operating System',
        'tc_applicationName': 'Application Name',
        'tc_softwareVersion': 'Software Version',
        'tc_affectedLocation': 'Affected Location',
        'tc_affectedUsers': 'Affected Users',
        'tc_internetStatus': 'Internet Status',
        'tc_accountType': 'Account Type',
        'tc_loginIssueType': 'Login Issue Type',
        'tc_responseTarget': 'Response Target',
        'tc_estimatedResolution': 'Estimated Resolution',
        'tc_dragDropFiles': 'Drag & drop files here or',
        'tc_browseFiles': 'browse files',
        'tc_maxFiles': 'Maximum size 100MB per file.',
        'tc_preview': 'Preview',
        'tc_remove': 'Remove',
        'tc_workflowPreview': 'Workflow Preview',
        'tc_ticketSubmitted': 'Ticket Submitted',
        'tc_underInvestigation': 'Under Investigation',
        'tc_resolutionApplied': 'Resolution Applied',
        'tc_ticketClosed': 'Ticket Closed',
        'tc_supportHours': 'Support Hours',
        'tc_submissionTips': 'Submission Tips',
        'tc_draftSaved': 'Draft saved',
        'tc_ticketSuccessSummary': 'Your ticket has been successfully submitted. Our IT Support team will review it shortly.',
        'tc_viewTicket': 'View Ticket',
        'tc_continueAnyway': 'Continue Anyway',
        'tc_useExistingSolution': 'View Knowledge Base',
        'tc_severityCritical': 'System-wide outage or severe business impact. Requires immediate attention.',
        'tc_severityHigh': 'Significant impact on a department or critical application failure.',
        'tc_severityMedium': 'Standard support request for individual issues.',
        'tc_severityLow': 'Minor requests or inquiries with no operational impact.',
        'tc_noArticlesFound': 'No related articles found.',
        'tc_titlePlaceholder': 'e.g. Cannot connect to office Wi-Fi',
        'tc_descPlaceholder': 'Please describe your issue in detail...',
        'tc_titleHelp': 'Be as specific as possible to help us resolve it quickly.',
        'tc_hardware': 'Hardware',
        'tc_software': 'Software',
        'tc_network': 'Network',
        'tc_account': 'Account/Access',
        'tc_sla_critical_resp': '< 30 Mins',
        'tc_sla_critical_res': '< 4 Hours',
        'tc_sla_high_resp': '< 2 Hours',
        'tc_sla_high_res': '< 1 Business Day',
        'tc_sla_medium_resp': '< 4 Hours',
        'tc_sla_medium_res': '< 2 Business Days',
        'tc_sla_low_resp': '< 1 Business Day',
        'tc_sla_low_res': '< 5 Business Days',
        'tc_supportHoursVal': 'Support Hours: 08:00 - 17:00 (Mon-Fri)',
        'tc_outsideHoursMsg': 'Tickets created outside hours are queued for next business day.',
        'tc_saveAsDraft': 'Save as Draft',
        'tc_recommended': '(Recommended)',

        // Broadcast Create
        'brc_newBroadcast': 'New Broadcast',
        'brc_newBroadcastDesc': 'Compose and send a new notification to users.',
        'brc_infoNote': 'Broadcasts are sent to selected audiences immediately unless scheduled.',
        'brc_title': 'Broadcast Title',
        'brc_titlePlaceholder': 'Enter notification title',
        'brc_messageBody': 'Message Body',
        'brc_messagePlaceholder': 'Type the broadcast message...',
        'brc_typeTheme': 'Type / Theme',
        'brc_infoBlue': 'Info (Blue)',
        'brc_successGreen': 'Success (Green)',
        'brc_warningYellow': 'Warning (Yellow)',
        'brc_errorRed': 'Error (Red)',
        'brc_priority': 'Priority',
        'brc_low': 'Low',
        'brc_normal': 'Normal',
        'brc_high': 'High',
        'brc_urgent': 'Urgent',
        'brc_targetAudience': 'Target Audience',
        'brc_allUsers': 'All Users',
        'brc_specificRoles': 'Specific Roles',
        'brc_specificDepartments': 'Specific Departments',
        'brc_selectRoles': 'Select Roles',
        'brc_user': 'User',
        'brc_admin': 'Admin',
        'brc_deliveryNote': 'Broadcasts will be delivered to the in-app notification center.',
        'brc_sendBroadcast': 'Send Broadcast',
        'brc_scheduling': 'Scheduling',
        'brc_sendAt': 'Send At (Optional)',
        'brc_leaveBlank': 'Leave blank to send immediately.',
        'brc_useTemplate': 'Use Template',
        'brc_noTemplate': '-- No Template --',
        
        // Flash Messages
        'Ticket updated successfully.': 'Ticket updated successfully.',
        'Ticket assigned successfully.': 'Ticket assigned successfully.',
        'Ticket escalated successfully.': 'Ticket escalated successfully.',
        'Ticket created successfully.': 'Ticket created successfully.',
        'Broadcast created and queued.': 'Broadcast created and queued.',
        'Broadcast cancelled.': 'Broadcast cancelled.',
        'Settings updated successfully.': 'Settings updated successfully.',
        'Category created successfully.': 'Category created successfully.',
        'Category deleted successfully.': 'Category deleted successfully.',
        'Response created successfully.': 'Response created successfully.',
        'Response deleted successfully.': 'Response deleted successfully.',
        'Category toggled successfully.': 'Category toggled successfully.',
        'Response toggled successfully.': 'Response toggled successfully.',
    },
    id: {
        // General
        'dashboard': 'Beranda',
        'tickets': 'Tiket',
        'settings': 'Pengaturan',
        'profile': 'Profil',
        'logout': 'Keluar',
        'cancel': 'Batal',
        'confirm': 'Konfirmasi',
        'save': 'Simpan Perubahan',
        'edit': 'Ubah',
        'search': 'Cari...',
        'actions': 'Aksi',
        'delete': 'Hapus',
        'active': 'Aktif',
        'inactive': 'Nonaktif',
        'notifications': 'Notifikasi',
        'ticket': 'Tiket',
        'allTickets': 'Semua Tiket',
        'department': 'Departemen',
        'noData': 'Tidak ada data tersedia',
        
        // Auth
        'signIn': 'Masuk',
        'createAccount': 'Buat Akun',
        'email': 'Alamat Email',
        'password': 'Kata Sandi',
        'rememberMe': 'Ingat saya',
        'forgotPassword': 'Lupa Kata Sandi?',
        'noAccount': "Belum memiliki akun?",
        'registerHere': 'Daftar',
        'enterCredentials': 'Masukkan kredensial Anda untuk mengakses sistem.',
        'registerDesc': 'Daftar untuk mengirimkan permintaan dukungan IT.',
        
        // TopBar / Profile Dropdown
        'editProfile': 'Ubah Profil',
        'theme': 'Tampilan',
        'language': 'Bahasa Indonesia',
        'logoutConfirmTitle': 'Konfirmasi Keluar',
        'logoutConfirmDesc': 'Apakah Anda yakin ingin keluar dari akun Anda? Anda harus masuk kembali untuk mengakses tiket Anda.',
        'loggingOut': 'Keluar...',

        // Sidebar
        'myTickets': 'Tiket Saya',
        'createTicket': 'Buat Tiket',
        'reports': 'Laporan',
        'broadcast': 'Notifikasi',
        'adminDashboard': 'Beranda Admin',
        'auditLog': 'Log Audit',
        'documentation': 'Dokumentasi',
        'knowledgeBase': 'Basis Pengetahuan',
        'users': 'Pengguna',
        'notifications': 'Notifikasi',
        
        // Dashboard
        'totalTickets': 'Total Tiket',
        'closed': 'Selesai',
        'reopened': 'Dibuka kembali',
        'inProgress': 'Sedang Diproses',
        'open': 'Buka',
        'urgent': 'Mendesak',
        'unassigned': 'Belum Ditugaskan',
        'recentTickets': 'Tiket Terbaru',
        'viewAll': 'Lihat Semua',
        'welcomeBack': 'Selamat datang kembali',
        'quickActions': 'Aksi Cepat',
        'priorityQueue': 'Antrean Prioritas',
        'highPriority': 'Tiket prioritas tinggi dan belum ditugaskan',
        'allClear': 'Semua aman',
        'noUrgent': 'Tidak ada tiket mendesak yang memerlukan perhatian segera.',
        'recentActivity': 'Aktivitas Terbaru',
        'systemActions': 'Tindakan dan pembaruan sistem',
        'noRecentActivity': 'Tidak ada aktivitas terbaru',
        'systemEventsAppear': 'Peristiwa sistem akan muncul di sini.',
        'status': 'Status',
        'priority': 'Prioritas',
        'ticketId': 'ID Tiket',
        'title': 'Judul',
        'date': 'Tanggal',
        'admin': 'Admin',
        'userManagement': 'Manajemen Pengguna',
        'manageUsersDesc': 'Kelola akun pengguna dan peran.',
        'user': 'Pengguna',
        'department': 'Departemen',
        'role': 'Peran',
        'lastLogin': 'Terakhir Masuk',
        'joined': 'Bergabung',
        'never': 'Belum Pernah',
        'noUsersFound': 'Tidak ada pengguna yang ditemukan.',
        'showing': 'Menampilkan',
        'of': 'dari',
        'searchUsers': 'Cari nama, email, atau departemen...',

        // Profile Page
        'profileSettings': 'Pengaturan Profil',
        'profileSettingsDesc': 'Kelola detail dan preferensi akun Anda.',
        'personalInfo': 'Informasi Pribadi',
        'personalInfoDesc': 'Perbarui detail profil dasar Anda.',
        'fullName': 'Nama Lengkap',
        'changePhoto': 'Ubah Foto',
        'uploadPhoto': 'Unggah Foto',
        'cropPhoto': 'Potong foto Anda',
        'zoom': 'Perbesar',
        'security': 'Keamanan',
        'securityDesc': 'Kelola kata sandi dan pengaturan keamanan Anda.',
        'currentPassword': 'Kata Sandi Saat Ini',
        'newPassword': 'Kata Sandi Baru',
        'confirmPassword': 'Konfirmasi Kata Sandi',
        'updatePassword': 'Perbarui Kata Sandi',
        'saveChanges': 'Simpan Perubahan',
        'saving': 'Menyimpan...',
        
        // Notifications
        'stayUpdated': 'Tetap perbarui aktivitas tiket Anda.',
        'markAllAsRead': 'Tandai semua telah dibaca',
        'ticket': 'Tiket',
        'markRead': 'Tandai dibaca',
        'page': 'Halaman',
        'noNotifications': 'Tidak ada notifikasi',
        'allCaughtUp': 'Semua sudah beres.',
        'allTickets': 'Semua Tiket',
        'manageAllTickets': 'Kelola semua tiket dukungan di seluruh organisasi.',
        'filters': 'Filter',
        'searchPlaceholder': 'Cari ID, judul, atau pemohon...',
        'allStatus': 'Semua Status',
        'allPriority': 'Semua Prioritas',
        'allAssignee': 'Semua Petugas',
        'unassigned': 'Belum Ditugaskan',
        'low': 'Rendah',
        'medium': 'Sedang',
        'high': 'Tinggi',
        'critical': 'Kritis',
        'exportCsv': 'Ekspor CSV',
        'id': 'ID',
        'requester': 'Pemohon',
        'category': 'Kategori',
        'assigned': 'Ditugaskan',
        'noTicketsFound': 'Tidak ada tiket ditemukan',
        'adjustFilters': 'Coba sesuaikan filter Anda.',
        'systemReports': 'Laporan Sistem',
        'reportsDesc': 'Metrik analitik dan kinerja.',
        'filter': 'Filter',
        'closedTickets': 'Tiket Selesai',
        'resolutionRate': 'Tingkat Penyelesaian',
        'avgResolution': 'Rata-rata Penyelesaian (Hari)',
        'ticketsByStatus': 'Tiket berdasarkan Status',
        'ticketsByPriority': 'Tiket berdasarkan Prioritas',
        'ticketsByCategory': 'Tiket berdasarkan Kategori',
        'ticketVolumeTrend': 'Tren Volume Tiket',
        'noData': 'Tidak ada data tersedia.',
        'noTicketData': 'Tidak ada data tiket untuk periode ini.',
        'auditLogDesc': 'Riwayat aktivitas sistem dan jejak audit.',
        'allActions': 'Semua Aksi',
        'searchDesc': 'Cari deskripsi...',
        'action': 'Aksi',
        'description': 'Deskripsi',
        'ip': 'IP',
        'noAuditLogs': 'Tidak ada log audit ditemukan.',
        'systemSettings': 'Pengaturan Sistem',
        'settingsDesc': 'Konfigurasi parameter sistem dan kategori tiket.',
        'configuration': 'Konfigurasi',
        'ticketCategories': 'Kategori Tiket',
        'cannedResponses': 'Tanggapan Cepat',
        'addCategory': 'Tambah Kategori Tiket',
        'addCategoryDesc': 'Buat kategori baru untuk tiket dukungan.',
        'categoryName': 'Nama Kategori',
        'categoryDesc': 'Deskripsi (Opsional)',
        'briefDesc': 'Deskripsi singkat tentang kategori ini',
        'manageCategories': 'Kelola Kategori',
        'manageCategoriesDesc': 'Aktifkan atau nonaktifkan kategori untuk tiket baru.',
        'name': 'Nama',
        'disable': 'Nonaktifkan',
        'enable': 'Aktifkan',
        'noCategories': 'Tidak ada kategori ditemukan.',
        'addMacro': 'Tambah Tanggapan Cepat',
        'addMacroDesc': 'Buat templat balasan untuk tanggapan cepat.',
        'templateTitle': 'Judul Templat',
        'responseBody': 'Isi Tanggapan',
        'writeTemplate': 'Tulis konten templat di sini...',
        'addTemplate': 'Tambah Templat',
        'manageMacros': 'Kelola Tanggapan Cepat',
        'manageMacrosDesc': 'Aktifkan atau nonaktifkan templat.',
        'noTemplates': 'Tidak ada templat ditemukan.',
        
        // Profile additional
        'phoneNumber': 'Nomor Telepon',
        'phonePlaceholder': '081234567890',
        'phoneHint': 'Hanya angka, 9–15 digit.',
        'departmentAdminOnly': 'Departemen hanya dapat diubah oleh Admin.',
        'contactAdminToChange': 'Hubungi administrator untuk mengubah.',
        'min8chars': 'Minimal 8 karakter',

        // Broadcast
        'broadcastNotification': 'Notifikasi Siaran',
        'broadcastDesc': 'Kirim peringatan sistem atau pesan ke pengguna.',
        'messageContent': '1. Isi Pesan',
        'notificationTitle': 'Judul Notifikasi',
        'egMaintenance': 'mis. Pemeliharaan Sistem',
        'messageLabel': 'Pesan',
        'enterDetails': 'Masukkan detail notifikasi...',
        'typeLabel': 'Tipe',
        'infoBlue': 'Info (Biru)',
        'successGreen': 'Sukses (Hijau)',
        'warningYellow': 'Peringatan (Kuning)',
        'errorRed': 'Kesalahan (Merah)',
        'targetAudience': '2. Target Pengguna',
        'allUsers': 'Semua Pengguna',
        'everyoneInSystem': 'Semua orang dalam sistem',
        'byDepartment': 'Berdasarkan Departemen',
        'specificDepartment': 'Departemen tertentu',
        'specificUsers': 'Pengguna Tertentu',
        'selectIndividuals': 'Pilih individu',
        'selectDepartment': 'Pilih Departemen',
        'selectADepartment': 'Pilih departemen...',
        'usersSelected': 'pengguna dipilih',
        'sendBroadcast': 'Kirim Notifikasi',
        'broadcastDetail': 'Detail siaran dan log pengiriman.',
        'broadcastContent': 'Konten Siaran',
        'creator': 'Pembuat',
        'sentAt': 'Terkirim Pada',
        'audience': 'Audiens',
        'channel': 'Saluran',
        'deliveryLog': 'Log Pengiriman',
        'recipients': 'penerima',
        'readAt': 'Dibaca Pada',
        'delivered': 'Terkirim',
        'noDeliveryLogs': 'Tidak ada log pengiriman tersedia.',
        'searchUsersDot': 'Cari pengguna...',
        'confirmDeleteCategory': 'Apakah Anda yakin ingin menghapus kategori ini?',
        'confirmDeleteMacro': 'Apakah Anda yakin ingin menghapus templat ini?',
        'td_escalation': 'Eskalasi',
        'td_escalated': 'Dieskalasi',
        'td_escalationReason': 'Alasan eskalasi',
        'td_escalationReasonPlaceholder': 'Alasan eskalasi...',
        'td_escalateTicket': 'Eskalasi Tiket',
        'td_escalateFurther': 'Eskalasi Lebih Lanjut',
        'draft': 'Draf',
        'reopened': 'Dibuka kembali',
        'open': 'Buka',
        'inProgress': 'Diproses',
        'closed': 'Selesai',
        'td_invalidTransition': 'Tidak dapat melakukan perubahan status ini.',

        // Flash Messages
        'td_ticketCreatedSuccess': 'Tiket berhasil dibuat.',
        'td_ticketUpdatedSuccess': 'Tiket berhasil diperbarui.',
        'td_ticketReopenedSuccess': 'Tiket berhasil dibuka kembali.',
        'td_ticketDeletedSuccess': 'Tiket berhasil dihapus.',
        'td_ticketAssignedSuccess': 'Tiket berhasil ditugaskan.',
        'td_ticketEscalatedSuccess': 'Tiket berhasil dieskalasi.',
        'td_feedbackThanks': 'Terima kasih atas umpan balik Anda!',
        'td_rateClosedOnly': 'Anda hanya dapat memberikan rating pada tiket yang sudah selesai.',
        'td_commentPosted': 'Komentar berhasil dikirim.',
        'td_profileUpdated': 'Profil berhasil diperbarui.',
        'td_passwordChanged': 'Kata sandi berhasil diubah.',
        'td_photoUpdated': 'Foto profil berhasil diperbarui.',
        'td_photoRemoved': 'Foto profil berhasil dihapus.',
        'td_coverUpdated': 'Foto sampul berhasil diperbarui.',
        'td_coverRemoved': 'Foto sampul berhasil dihapus.',
        'td_preferencesUpdated': 'Preferensi berhasil diperbarui.',
        'td_draftNotice': 'Tiket ini masih berstatus draf.',
        'td_draftNoticeDesc': 'Kirim tiket ini ketika Anda siap mengirimkannya ke tim IT Support.',
        'td_submitDraft': 'Kirim Tiket',
        'td_editDraft': 'Edit Draf',
        'td_draftSubmittedSuccess': 'Draf berhasil dikirim.',
        'td_allNotificationsRead': 'Semua notifikasi ditandai sudah dibaca.',
        'td_notificationDeleted': 'Notifikasi berhasil dihapus.',
        'td_readNotificationsCleared': 'Notifikasi yang sudah dibaca berhasil dihapus.',
        'tc_addAttachments': 'Tambah Lampiran',

        // Profile Extended
        'profileInformation': 'Informasi Profil',
        'preferences': 'Preferensi',
        'activity': 'Log Aktivitas',
        'languagePref': 'Preferensi Bahasa',
        'notificationPref': 'Preferensi Notifikasi',
        'selectLanguage': 'Pilih Bahasa',
        'english': 'Bahasa Inggris',
        'indonesian': 'Bahasa Indonesia',
        'emailNotifications': 'Notifikasi Email',
        'appNotifications': 'Notifikasi Dalam Aplikasi',
        'receiveEmailUpdates': 'Terima pembaruan tentang tiket via email',
        'receiveAppUpdates': 'Terima notifikasi sistem di aplikasi',
        'auditHistory': 'Riwayat Audit',
        'noActivityLogs': 'Tidak ada log aktivitas.',
        'accountSummary': 'Ringkasan Akun',
        'roleLabel': 'Peran',
        'departmentLabel': 'Departemen',
        'joinedLabel': 'Bergabung',
        'lastLoginLabel': 'Terakhir Masuk',
        'removePhoto': 'Hapus Foto',
        'uploading': 'Mengunggah...',
        'removing': 'Menghapus...',
        'cancelCrop': 'Batal',
        'applyCrop': 'Terapkan',
        'cropPhoto': 'Potong Foto',
        'zoom': 'Perbesar',

        // Ticket Create/Index (User)
        'createNewTicket': 'Buat Tiket Baru',
        'createTicketDesc': 'Jelaskan masalah Anda dan kami akan membantu secepatnya.',
        'titleHelpText': 'Jelaskan masalah secara singkat.',
        'titlePlaceholder': 'mis. Printer tidak berfungsi di Ruang 204',
        'selectCategory': 'Pilih kategori',

        // Broadcast Create
        'brc_newBroadcast': 'Siaran Baru',
        'brc_newBroadcastDesc': 'Buat dan kirim notifikasi baru ke pengguna.',
        'brc_infoNote': 'Siaran dikirim ke pengguna yang dipilih secara langsung kecuali dijadwalkan.',
        'brc_title': 'Judul Siaran',
        'brc_titlePlaceholder': 'Masukkan judul notifikasi',
        'brc_messageBody': 'Isi Pesan',
        'brc_messagePlaceholder': 'Ketik isi pesan siaran...',
        'brc_typeTheme': 'Tipe / Tema',
        'brc_infoBlue': 'Info (Biru)',
        'brc_successGreen': 'Sukses (Hijau)',
        'brc_warningYellow': 'Peringatan (Kuning)',
        'brc_errorRed': 'Kesalahan (Merah)',
        'brc_priority': 'Prioritas',
        'brc_low': 'Rendah',
        'brc_normal': 'Normal',
        'brc_high': 'Tinggi',
        'brc_urgent': 'Mendesak',
        'brc_targetAudience': 'Target Pengguna',
        'brc_allUsers': 'Semua Pengguna',
        'brc_specificRoles': 'Peran Tertentu',
        'brc_specificDepartments': 'Departemen Tertentu',
        'brc_selectRoles': 'Pilih Peran',
        'brc_user': 'Pengguna',
        'brc_admin': 'Admin',
        'brc_deliveryNote': 'Siaran akan dikirim ke pusat notifikasi dalam aplikasi.',
        'brc_sendBroadcast': 'Kirim Siaran',
        'brc_scheduling': 'Penjadwalan',
        'brc_sendAt': 'Kirim Pada (Opsional)',
        'brc_leaveBlank': 'Kosongkan untuk mengirim segera.',
        'brc_useTemplate': 'Gunakan Templat',
        'brc_noTemplate': '-- Tanpa Templat --',
        
        // Flash Messages
        'Ticket updated successfully.': 'Tiket berhasil diperbarui.',
        'Ticket assigned successfully.': 'Tiket berhasil ditugaskan.',
        'Ticket escalated successfully.': 'Tiket berhasil dieskalasi.',
        'Ticket created successfully.': 'Tiket berhasil dibuat.',
        'Broadcast created and queued.': 'Notifikasi dibuat dan masuk antrean.',
        'Broadcast cancelled.': 'Notifikasi dibatalkan.',
        'Settings updated successfully.': 'Pengaturan berhasil diperbarui.',
        'Category created successfully.': 'Kategori berhasil dibuat.',
        'Category deleted successfully.': 'Kategori berhasil dihapus.',
        'Response created successfully.': 'Tanggapan berhasil dibuat.',
        'Response deleted successfully.': 'Tanggapan berhasil dihapus.',
        'Category toggled successfully.': 'Status kategori berhasil diubah.',
        'Response toggled successfully.': 'Status tanggapan berhasil diubah.',

        'low': 'Rendah',
        'medium': 'Sedang',
        'high': 'Tinggi',
        'critical': 'Kritis',
        'descriptionPlaceholder': 'Berikan informasi lengkap termasuk langkah-langkah untuk mereproduksi masalah.',
        'attachmentsOptional': 'Lampiran (opsional)',
        'attachmentHint': 'Maks 5 berkas, 10MB per berkas. Didukung: gambar, PDF, dokumen Office, markdown, ZIP.',
        'submitTicket': 'Kirim Tiket',
        'trackTicketsDesc': 'Lacak dan kelola permintaan dukungan Anda.',
        'newTicket': 'Tiket Baru',
        'searchByIdOrTitle': 'Cari berdasarkan ID atau judul...',
        'reopened': 'Dibuka Kembali',
        'createFirstTicket': 'Buat tiket pertama Anda untuk memulai.',
        'notifications': 'Notifikasi',

        // Notification Operations Center
        'notificationOperationsCenter': 'Pusat Operasi Notifikasi',
        'notificationOperationsCenterDesc': 'Kelola siaran, templat, dan notifikasi otomatis.',
        'newBroadcast': 'Siaran Baru',
        'overview': 'Ringkasan',
        'broadcasts': 'Siaran',
        'templates': 'Templat',
        'automation': 'Otomasi',
        'totalBroadcasts': 'Total Siaran',
        'completed': 'Selesai',
        'scheduled': 'Terjadwal',
        'failed': 'Gagal',
        'recentBroadcasts': 'Siaran Terbaru',
        'viewAll': 'Lihat Semua',
        'type': 'Tipe',
        'noBroadcastsFound': 'Belum ada siaran',
        'noBroadcastsDesc': 'Anda belum mengirim siaran apa pun.',
        'createBroadcast': 'Buat Siaran',
        'systemCapacity': 'Kapasitas Sistem',
        'monthlyQuota': 'Kuota Bulanan',
        'unlimited': 'Tak Terbatas',
        'info': 'Info',
        'success': 'Berhasil',
        'warning': 'Peringatan',
        'error': 'Kesalahan',
        'draft': 'Draf',
        'processing': 'Diproses',

        // Reports Dashboard
        'rpt_title': 'Dasbor Pelaporan',
        'rpt_subtitle': 'Analitik komprehensif dan wawasan kinerja.',
        'rpt_tickets': 'Tiket',
        'rpt_opened': 'Dibuka',
        'rpt_resolved': 'Diselesaikan',
        'rpt_pending': 'Tertunda',
        'rpt_overdue': 'Terlambat',
        'rpt_avgResTime': 'Rata-rata Resolusi',
        'rpt_slaCompliance': 'Kepatuhan SLA',
        'rpt_resolvedToday': 'Diselesaikan Hari Ini',
        'rpt_reopened': 'Dibuka Kembali',
        'rpt_satisfaction': 'Kepuasan',
        'rpt_vsPrev': 'vs periode sebelumnya',
        'rpt_openVsResolved': 'Dibuka vs Diselesaikan',
        'rpt_openVsResolvedDesc': 'Bandingkan tiket baru terhadap throughput penyelesaian.',
        'rpt_resolutionTrend': 'Tren Waktu Resolusi',
        'rpt_resolutionTrendDesc': 'Rata-rata waktu resolusi dalam jam per hari.',
        'rpt_slaOverview': 'Ringkasan SLA',
        'rpt_compliance': 'Kepatuhan',
        'rpt_withinSla': 'Dalam SLA',
        'rpt_breached': 'Dilanggar',
        'rpt_slaTrend': 'Tren Kepatuhan SLA',
        'rpt_slaTrendDesc': 'Tingkat kepatuhan SLA harian dari waktu ke waktu.',
        'rpt_techPerformance': 'Kinerja Teknisi',
        'rpt_techPerformanceDesc': 'Rincian beban kerja per teknisi.',
        'rpt_activityHeatmap': 'Peta Panas Aktivitas',
        'rpt_activityHeatmapDesc': 'Pola pembuatan tiket berdasarkan hari dan jam.',
        'rpt_less': 'Sedikit',
        'rpt_more': 'Banyak',
        'rpt_lifecycle': 'Corong Siklus Hidup Tiket',
        'rpt_lifecycleDesc': 'Alur dari pembuatan hingga penyelesaian.',
        'rpt_reopenedAnalytics': 'Tiket Dibuka Kembali',
        'rpt_reopenedCount': 'Dibuka Kembali',
        'rpt_reopenRate': 'Tingkat Pembukaan Kembali',
        'rpt_prevPeriod': 'Periode Sblm.',
        'rpt_reopenedInsight': 'Tingkat pembukaan kembali yang tinggi dapat mengindikasikan resolusi awal yang tidak tuntas atau definisi masalah yang kurang jelas.',
        'rpt_avgRating': 'Rata-rata Penilaian',
        'rpt_ratings': 'penilaian',
        'rpt_avgHours': 'Rata-rata Jam',
        'rpt_export': 'Ekspor',
        'rpt_today': 'Hari Ini',
        'rpt_7d': '7 Hari',
        'rpt_30d': '30 Hari',
        'rpt_90d': '90 Hari',

        // Ticket Detail
        'td_description': 'Deskripsi',
        'td_solutionNotes': 'Catatan Solusi',
        'td_attachments': 'Lampiran',
        'td_activity': 'Aktivitas',
        'td_noActivity': 'Belum ada aktivitas.',
        'td_writeComment': 'Tulis komentar...',
        'td_writeCommentAdmin': 'Tulis komentar atau catatan internal...',
        'td_internalNote': 'Catatan internal',
        'td_internalNoteDesc': 'Catatan internal (tidak terlihat oleh pengguna)',
        'td_postComment': 'Kirim Komentar',
        'td_post': 'Kirim',
        'td_details': 'Detail',
        'td_requester': 'Pemohon',
        'td_assignedTo': 'Ditugaskan Kepada',
        'td_unassigned': 'Belum Ditugaskan',
        'td_created': 'Dibuat',
        'td_estimatedResolution': 'Estimasi Penyelesaian',
        'td_slaDeadline': 'Batas Waktu SLA',
        'td_responseDeadline': 'Batas Waktu Respon',
        'td_firstRespondedAt': 'Respon Pertama',
        'td_escalationLevel': 'Tingkat Eskalasi',
        'td_escalatedAt': 'Dieskalasi Pada',
        'td_escalationReason': 'Alasan Eskalasi',
        'td_escalated': 'Dieskalasi',
        'td_escalation': 'Eskalasi',
        'td_escalateFurther': 'Eskalasi Lebih Lanjut',
        'td_escalateTicket': 'Eskalasi Tiket',
        'td_escalationReasonPlaceholder': 'Alasan eskalasi...',
        'td_draftNotice': 'Tiket ini masih berupa draf.',
        'td_draftNoticeDesc': 'Kirim tiket ini saat Anda sudah siap meneruskannya ke tim IT Support.',
        'td_submitDraft': 'Kirim Tiket',
        'td_closed': 'Ditutup',
        
        // Duplicates
        'similarTicketsFound': 'Tiket Terbuka Serupa Ditemukan',
        'similarTicketsDesc': 'Sebelum mengirim, silakan periksa apakah tiket yang serupa ini sudah mengatasi masalah Anda:',
        'viewTicket': 'Lihat Tiket',
        'td_yourFeedback': 'Umpan Balik Anda',
        'td_rateExperience': 'Beri penilaian pengalaman Anda',
        'td_rateDesc': 'Seberapa puas Anda dengan penyelesaian tiket ini?',
        'td_additionalFeedback': 'Umpan balik tambahan? (Opsional)',
        'td_submitFeedback': 'Kirim Umpan Balik',
        'td_issueNotResolved': 'Masalah belum selesai?',
        'td_issueNotResolvedDesc': 'Jika Anda masih mengalami masalah yang sama, Anda dapat membuka kembali tiket ini.',
        'td_reopenTicket': 'Buka Kembali Tiket',
        'td_files': 'berkas',
        'td_internal': 'Internal',
        'td_assignedToBy': 'Ditugaskan kepada',
        'td_by': 'oleh',
        'td_updateStatus': 'Perbarui Status',
        'td_addResolutionDetails': 'Tambahkan detail penyelesaian...',
        'td_assignTicket': 'Tugaskan Tiket',
        'td_assignTo': 'Tugaskan Kepada',
        'td_selectStaff': 'Pilih anggota staf',
        'td_assignmentNotes': 'Catatan (opsional)',
        'td_assignmentNotesPlaceholder': 'Catatan penugasan...',
        'td_assign': 'Tugaskan',
        'td_insertTemplate': 'Sisipkan templat...',
        'td_userSatisfaction': 'Kepuasan Pengguna',
        'td_name': 'Nama',

        // Notification Templates
        'nt_templates': 'Templat Notifikasi',
        'nt_templatesDesc': 'Kelola templat notifikasi yang dapat digunakan kembali untuk siaran dan otomatisasi.',
        'nt_newTemplate': 'Templat Baru',
        'nt_searchTemplates': 'Cari templat...',
        'nt_noTemplatesYet': 'Belum ada templat yang dibuat.',
        'nt_noMatchingTemplates': 'Tidak ada templat yang cocok.',
        'nt_createFirstTemplate': 'Buat templat pertama Anda',
        'nt_templatePreview': 'Pratinjau Templat',
        'nt_templateName': 'Nama Templat',
        'nt_subject': 'Subjek',
        'nt_content': 'Konten',
        'nt_variables': 'Variabel',
        'nt_preview': 'Pratinjau',
        'nt_confirmDelete': 'Apakah Anda yakin ingin menghapus templat ini?',
        'nt_deactivate': 'Nonaktifkan',
        'nt_activate': 'Aktifkan',

        // Notification Automation
        'na_automation': 'Otomatisasi Notifikasi',
        'na_automationDesc': 'Konfigurasi aturan notifikasi otomatis berdasarkan peristiwa sistem.',
        'na_newRule': 'Aturan Baru',
        'na_searchRules': 'Cari aturan...',
        'na_noRulesYet': 'Belum ada aturan otomatisasi.',
        'na_noMatchingRules': 'Tidak ada aturan yang cocok.',
        'na_createFirstRule': 'Buat aturan otomatisasi pertama Anda',
        'na_totalRules': 'Total Aturan',
        'na_confirmDelete': 'Apakah Anda yakin ingin menghapus aturan otomatisasi ini?',
        'na_createRuleDesc': 'Tentukan peristiwa pemicu dan hubungkan ke templat notifikasi.',
        'na_ruleName': 'Nama Aturan',
        'na_ruleNamePlaceholder': 'mis. Notifikasi saat tiket dibuat',
        'na_triggerEvent': 'Peristiwa Pemicu',
        'na_selectEvent': 'Pilih peristiwa pemicu...',
        'na_template': 'Templat Notifikasi',
        'na_selectTemplate': 'Pilih templat...',
        'na_actionConfig': 'Konfigurasi Aksi',
        'na_inAppNotification': 'Notifikasi Dalam Aplikasi',
        'na_inAppDesc': 'Tampilkan notifikasi di panel notifikasi pengguna.',
        'na_emailNotification': 'Notifikasi Email',
        'na_emailDesc': 'Kirim email ke pengguna terkait.',
        'na_activeOnCreateDesc': 'Aturan akan langsung mulai memproses peristiwa.',
        'na_createRule': 'Buat Aturan',

        // Template Create
        'nt_createTemplateDesc': 'Buat templat notifikasi yang dapat digunakan kembali dengan variabel dinamis.',
        'nt_templateNamePlaceholder': 'mis. Pembaruan Status Tiket',
        'nt_subjectPlaceholder': 'mis. Tiket #{{ticket_number}} Anda telah diperbarui',
        'nt_contentPlaceholder': 'Tulis konten notifikasi di sini. Gunakan sintaks {{variabel}} untuk nilai dinamis.',
        'nt_variablesHint': 'Tentukan variabel yang dapat digunakan di subjek dan konten. Klik variabel untuk menyisipkannya ke konten.',
        'nt_addVariablePlaceholder': 'Nama variabel (mis. ticket_number)',
        'nt_clickToInsert': 'Klik untuk menyisipkan ke konten',
        'nt_activeOnCreate': 'Aktif saat pembuatan',
        'nt_activeOnCreateDesc': 'Templat akan segera tersedia untuk digunakan.',
        'nt_createTemplate': 'Buat Templat',

        // User Notifications Page
        'nf_subtitle': 'Tetap terbarui dengan aktivitas tiket dan pemberitahuan sistem.',
        'nf_all': 'Semua',
        'nf_unread': 'Belum Dibaca',
        'nf_read': 'Sudah Dibaca',
        'nf_clearRead': 'Hapus Dibaca',
        'nf_totalNotifications': 'Total',
        'nf_today': 'Hari Ini',
        'nf_details': 'Detail',
        'nf_message': 'Pesan',
        'nf_assignedTo': 'Ditugaskan Ke',
        'nf_time': 'Waktu',
        'nf_viewTicket': 'Lihat Tiket',
        'nf_total': 'total',
        'nf_emptyDesc': 'Saat Anda menerima notifikasi tentang pembaruan tiket, mereka akan muncul di sini.',
        'nf_confirmClearRead': 'Apakah Anda yakin ingin menghapus semua notifikasi yang sudah dibaca?',

        // Admin Notification Dashboard
        'nda_title': 'Pusat Operasi Notifikasi',
        'nda_subtitle': 'Kelola siaran, templat, otomatisasi, dan pantau notifikasi sistem.',
        'nda_overviewDesc': 'Dasbor & Metrik',
        'nda_broadcastsDesc': 'Kirim & kelola',
        'nda_rulesActive': 'aturan aktif',
        'nda_systemNotifs': 'Notif Sistem',
        'nda_recentSystemNotifs': 'Notifikasi Sistem Terbaru',
        'nda_recentSystemNotifsDesc': 'Notifikasi terbaru di semua pengguna.',
        'nda_noSystemNotifs': 'Belum ada notifikasi sistem.',
        'nda_broadcastsTableDesc': '5 pesan siaran terakhir.',
        'nda_by': 'oleh',
        'nda_automationRules': 'Aturan Otomatisasi',
        'nda_monthlyQuota': 'Kuota Bulanan',
        'nda_draft': 'Draf',
        'nda_processing': 'Memproses',
        'nda_info': 'Info',
        'nda_success': 'Sukses',
        'nda_danger': 'Berbahaya',

        // Ticket Create (New Enterprise Workflow)
        'tc_issueInfo': 'Informasi Masalah',
        'tc_ticketClassification': 'Klasifikasi Tiket',
        'tc_issueDescription': 'Deskripsi Detail Masalah',
        'tc_smartRecommendations': 'Rekomendasi Cerdas',
        'tc_attachments': 'Lampiran & Bukti',
        'tc_slaWorkflowInfo': 'Informasi SLA & Alur Kerja',
        'tc_operationalGuidance': 'Panduan Operasional',
        'tc_submissionConfirmation': 'Konfirmasi Pengiriman',
        'tc_suggestedPriority': 'Prioritas Disarankan',
        'tc_suggestedCategory': 'Kategori Disarankan',
        'tc_estimatedSLA': 'Estimasi SLA',
        'tc_recommendedDept': 'Departemen Disarankan',
        'tc_issueSeverity': 'Tingkat Keparahan',
        'tc_relatedArticles': 'Artikel Basis Pengetahuan Terkait',
        'tc_possibleSimilarTickets': 'Kemungkinan Tiket Serupa',
        'tc_deviceType': 'Tipe Perangkat',
        'tc_assetNumber': 'Nomor Aset',
        'tc_physicalLocation': 'Lokasi Fisik',
        'tc_hardwareModel': 'Model Perangkat Keras',
        'tc_operatingSystem': 'Sistem Operasi',
        'tc_applicationName': 'Nama Aplikasi',
        'tc_softwareVersion': 'Versi Perangkat Lunak',
        'tc_affectedLocation': 'Lokasi Terdampak',
        'tc_affectedUsers': 'Pengguna Terdampak',
        'tc_internetStatus': 'Status Internet',
        'tc_accountType': 'Tipe Akun',
        'tc_loginIssueType': 'Tipe Kendala Login',
        'tc_responseTarget': 'Target Respon',
        'tc_estimatedResolution': 'Estimasi Penyelesaian',
        'tc_dragDropFiles': 'Tarik & lepas file di sini atau',
        'tc_browseFiles': 'pilih file',
        'tc_maxFiles': 'Ukuran maksimal 100MB per berkas.',
        'tc_preview': 'Pratinjau',
        'tc_remove': 'Hapus',
        'tc_workflowPreview': 'Pratinjau Alur Kerja',
        'tc_ticketSubmitted': 'Tiket Dibuat',
        'tc_underInvestigation': 'Dalam Pemeriksaan',
        'tc_resolutionApplied': 'Penyelesaian Diterapkan',
        'tc_ticketClosed': 'Tiket Ditutup',
        'tc_supportHours': 'Jam Operasional',
        'tc_submissionTips': 'Tips Pembuatan Tiket',
        'tc_draftSaved': 'Draf tersimpan',
        'tc_ticketSuccessSummary': 'Tiket Anda berhasil dikirim. Tim IT Support kami akan segera meninjaunya.',
        'tc_viewTicket': 'Lihat Tiket',
        'tc_continueAnyway': 'Tetap Lanjutkan',
        'tc_useExistingSolution': 'Lihat Basis Pengetahuan',
        'tc_severityCritical': 'Gangguan sistem meluas atau berdampak parah. Butuh penanganan segera.',
        'tc_severityHigh': 'Berdampak signifikan pada departemen atau kegagalan aplikasi kritis.',
        'tc_severityMedium': 'Permintaan dukungan standar untuk kendala individu.',
        'tc_severityLow': 'Permintaan minor atau pertanyaan tanpa dampak operasional.',
        'tc_noArticlesFound': 'Tidak ada artikel terkait yang ditemukan.',
        'tc_titlePlaceholder': 'misal: Tidak dapat terhubung ke Wi-Fi kantor',
        'tc_descPlaceholder': 'Jelaskan masalah Anda secara detail...',
        'tc_titleHelp': 'Berikan informasi spesifik agar kami dapat menyelesaikannya dengan cepat.',
        'tc_hardware': 'Perangkat Keras',
        'tc_software': 'Perangkat Lunak',
        'tc_network': 'Jaringan',
        'tc_account': 'Akun/Akses',
        'tc_sla_critical_resp': '< 30 Menit',
        'tc_sla_critical_res': '< 4 Jam',
        'tc_sla_high_resp': '< 2 Jam',
        'tc_sla_high_res': '< 1 Hari Kerja',
        'tc_sla_medium_resp': '< 4 Jam',
        'tc_sla_medium_res': '< 2 Hari Kerja',
        'tc_sla_low_resp': '< 1 Hari Kerja',
        'tc_sla_low_res': '< 5 Hari Kerja',
        'tc_supportHoursVal': 'Jam Operasional: 08:00 - 17:00 (Senin-Jumat)',
        'tc_outsideHoursMsg': 'Tiket yang dibuat di luar jam operasional akan diproses pada hari kerja berikutnya.',
        'tc_saveAsDraft': 'Simpan sebagai Draf',
        'tc_recommended': '(Disarankan)',
    }
};

export function LanguageProvider({ children }) {
    const [language, setLanguage] = useState('en');

    useEffect(() => {
        const savedLang = localStorage.getItem('app_language');
        if (savedLang && (savedLang === 'en' || savedLang === 'id')) {
            setLanguage(savedLang);
        }
    }, []);

    const changeLanguage = (lang) => {
        setLanguage(lang);
        localStorage.setItem('app_language', lang);
    };

    const t = (key) => {
        return translations[language][key] || translations['en'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    return useContext(LanguageContext);
}
